unit DAC.Components.DesignSystem.ControlTokens;

interface

uses
  System.UITypes;

const
  // Kept as a compile-time constant so the published DFM default remains
  // stable while the runtime metric is resolved through ButtonDefaultCornerRadius.
  DACButtonDefaultCornerRadius = 8;
  DACDataGridDefaultCornerRadius = 8;
  DACButtonEditDefaultButtonWidth = 48;
  DACButtonEditDefaultCornerRadius = 8;
  DACEditDefaultCornerRadius = 8;
  DACComboBoxDefaultCornerRadius = 8;
  DACDateTimeDefaultCornerRadius = 8;
  DACMemoDefaultCornerRadius = 8;
  DACContainerDefaultRadius = 10;
  DACContainerDefaultBorderWidth = 1;
  DACContainerDefaultPadding = 16;
  DACContainerDefaultHeaderHeight = 42;
  DACGridContainerDefaultRadius = 8;
  DACGridContainerDefaultGutter = 16;
  DACGridContainerDefaultPadding = 24;
  DACGridContainerDefaultRowHeight = 64;
  DACBadgeDefaultCornerRadius = 10;
  DACScrollContainerDefaultCornerRadius = 8;
  DACSummaryCardDefaultCornerRadius = 10;
  DACTabsDefaultCornerRadius = 8;
  // Surface classification deliberately leaves a neutral band. Mid-tone
  // container colors do not guess a theme and let the next visual ancestor
  // decide instead.
  DACSurfaceDarkLuminanceMax = 104;
  DACSurfaceLightLuminanceMin = 152;

type
  TDACControlSizeTokens = record
    Height: Single;
    PaddingHorizontal: Single;
    PaddingVertical: Single;
    IconSize: Single;
    TextSize: Single;
    NativeFontSize: Single;
  end;

  // Component-specific visual contract reconstructed from the reference
  // boards. Controls consume this record instead of carrying measurements.
  // AGREGADOR: Este record mantem a compatibilidade de DFM completa.
  // Futuras refatoracoes migrarao gradualmente para os 7 records de dominio.
  TDACControlTokens = record
    ButtonSmall: TDACControlSizeTokens;
    ButtonMedium: TDACControlSizeTokens;
    ButtonLarge: TDACControlSizeTokens;
    // Shared painter fallbacks. Future consumers use semantic contracts
    // rather than repeating opaque/transparent literals.
    AlphaOpaque: Byte;
    TransparentSurfaceFallback: TAlphaColor;
    BadgeDefaultWidth: Single;
    BadgeDefaultHeight: Single;
    ChartDefaultWidth: Single;
    ChartDefaultHeight: Single;
    ContainerDefaultWidth: Single;
    ContainerDefaultHeight: Single;
    DataGridDefaultWidth: Single;
    DataGridDefaultHeight: Single;
    ToastDefaultWidth: Single;
    ToastDefaultHeight: Single;
    ModalDefaultWidth: Single;
    ModalDefaultHeight: Single;
    TooltipDefaultWidth: Single;
    TooltipDefaultHeight: Single;
    GridContainerDefaultWidth: Single;
    GridContainerDefaultHeight: Single;
    GridContainerDefaultColumns: Integer;
    GridContainerMinimumChildWidth: Single;
    GridContainerMinimumRowHeight: Single;
    ComboBoxDefaultDropDownCount: Integer;
    LoadingDefaultWidth: Single;
    LoadingDefaultHeight: Single;
    PaginationDefaultWidth: Single;
    PaginationDefaultHeight: Single;
    PaginationDefaultPageCount: Integer;
    PaginationDefaultPageIndex: Integer;
    PaginationDefaultPageSize: Integer;
    PaginationVisiblePageButtonCount: Integer;
    ProgressDefaultWidth: Single;
    ProgressDefaultHeight: Single;
    ReportViewerDefaultWidth: Single;
    ReportViewerDefaultHeight: Single;
    ScrollContainerDefaultWidth: Single;
    ScrollContainerDefaultHeight: Single;
    SelectorDefaultWidth: Single;
    SelectorDefaultHeight: Single;
    ToggleDefaultWidth: Single;
    ToggleDefaultHeight: Single;
    SliderDefaultWidth: Single;
    SliderDefaultHeight: Single;
    SkiaControlDefaultWidth: Single;
    SkiaControlDefaultHeight: Single;
    StatusBarDefaultWidth: Single;
    SummaryCardDefaultWidth: Single;
    SummaryCardDefaultHeight: Single;
    TabsDefaultWidth: Single;
    TabsDefaultHeight: Single;
    TabsSmall: TDACControlSizeTokens;
    TabsMedium: TDACControlSizeTokens;
    TabsLarge: TDACControlSizeTokens;
    // TDACButton owns a Skia palette, caption/icon layout and an optional
    // input-action divider. Keep its compatibility measurements and semantic
    // surfaces local instead of borrowing generic Input/Popup controls.
    ButtonDefaultWidth: Single;
    ButtonDefaultHeight: Single;
    ButtonDefaultCornerRadius: Single;
    ButtonCompactCornerRadius: Single;
    ButtonRoundedCornerRadius: Single;
    ButtonMaximumIconSize: Integer;
    ButtonContentGap: Single;
    ButtonMinimumWidth: Single;
    ButtonPainterSnapScale: Single;
    ButtonPainterInset: Single;
    ButtonBorderWidth: Single;
    ButtonInputActionDividerWidth: Single;
    ButtonInputActionDividerVerticalInset: Single;
    ButtonInputActionCaptionTextSize: Single;
    ButtonInputActionCaptionRightInset: Single;
    ButtonCaptionBold: Boolean;
    ButtonCaptionMaxLines: Integer;
    ButtonAlphaOpaque: Byte;
    ButtonBorderAlphaNone: Byte;
    ButtonBorderAlphaGhostNormal: Byte;
    ButtonBorderAlphaGhostActive: Byte;
    ButtonBorderAlphaFull: Byte;
    ButtonFallbackBackground: TAlphaColor;
    ButtonCanvasBackground: TAlphaColor;
    ButtonInputActionCanvasBackground: TAlphaColor;
    ButtonTransparent: TAlphaColor;
    ButtonPrimaryBackground: TAlphaColor;
    ButtonPrimaryHoverBackground: TAlphaColor;
    ButtonPrimaryPressedBackground: TAlphaColor;
    ButtonPrimaryText: TAlphaColor;
    ButtonSecondaryBackground: TAlphaColor;
    ButtonSecondaryHoverBackground: TAlphaColor;
    ButtonSecondaryPressedBackground: TAlphaColor;
    ButtonSecondaryBorder: TAlphaColor;
    ButtonSecondaryHoverBorder: TAlphaColor;
    ButtonSecondaryText: TAlphaColor;
    ButtonInputActionText: TAlphaColor;
    ButtonInputActionDivider: TAlphaColor;
    ButtonTransparentText: TAlphaColor;
    ButtonGhostBackground: TAlphaColor;
    ButtonGhostActiveBackground: TAlphaColor;
    ButtonGhostBorder: TAlphaColor;
    ButtonGhostText: TAlphaColor;
    ButtonDangerBackground: TAlphaColor;
    ButtonDangerText: TAlphaColor;
    ButtonWarningBackground: TAlphaColor;
    ButtonWarningHoverBackground: TAlphaColor;
    ButtonWarningPressedBackground: TAlphaColor;
    ButtonWarningText: TAlphaColor;
    ButtonDisabledBackground: TAlphaColor;
    ButtonDisabledBorder: TAlphaColor;
    ButtonDisabledText: TAlphaColor;
    ButtonLoadingBackground: TAlphaColor;
    ButtonLoadingBorder: TAlphaColor;
    ButtonLoadingText: TAlphaColor;
    // TDACButtonEdit host/button geometry is deliberately independent from
    // its TDACEdit and TDACButton children.
    ButtonEditDefaultWidth: Single;
    ButtonEditDefaultHeight: Single;
    ButtonEditDefaultButtonWidth: Single;
    ButtonEditDefaultCornerRadius: Single;
    ButtonEditButtonCornerRadius: Single;
    ButtonEditButtonGap: Single;
    ButtonEditButtonInset: Single;
    ButtonEditLabeledMinimumHeight: Single;
    InputSmall: TDACControlSizeTokens;
    InputMedium: TDACControlSizeTokens;
    InputLarge: TDACControlSizeTokens;
    BorderWidth: Single;
    FocusRingWidth: Single;
    ButtonRadius: Single;
    InputRadius: Single;
    ComboBoxRadius: Single;
    DateTimePickerRadius: Single;
    IconGap: Single;
    ButtonEditDividerWidth: Single;
    DropDownItemHeight: Single;
    PopupRadius: Single;
    PopupWidth: Single;
    PopupCalendarHeight: Single;
    PopupTimeHeight: Single;
    PopupOuterInset: Single;
    PopupHeaderHeight: Single;
    PopupNavigationSize: Single;
    PopupWeekHeaderHeight: Single;
    PopupCalendarCellHeight: Single;
    PopupDayRadius: Single;
    PopupFooterHeight: Single;
    PopupFooterActionWidth: Single;
    PopupOffset: Single;
    PopupHeaderGap: Single;
    PopupWeekTopGap: Single;
    PopupCalendarTopGap: Single;
    PopupTimeCaptionOffset: Single;
    PopupTimeValueTopOffset: Single;
    PopupTimeValueHeight: Single;
    PopupTimeActionInset: Single;
    PopupTimeActionGap: Single;
    PopupTimeHitPadding: Single;
    PopupWeekColumns: Integer;
    PopupTimeActionTop: Single;
    PopupTimeActionHeight: Single;
    PopupCaptionTextSize: Single;
    PopupBodyTextSize: Single;
    PopupTimeTextSize: Single;
    StatusBarHeight: Single;
    StatusBarInset: Single;
    StatusBarRadius: Single;
    StatusBarIndicatorRadius: Single;
    StatusBarTextSize: Single;
    StatusBarTextBaseline: Single;
    StatusBarLeftTextOffset: Single;
    StatusBarRightTextInset: Single;
    ProgressLinearThickness: Single;
    ProgressCircularThickness: Single;
    ProgressValueTextSize: Single;
    ProgressValueTextInset: Single;
    ProgressValueTextOffset: Single;
    ProgressDisabledAlpha: Byte;
    LoadingTimerInterval: Integer;
    LoadingSpinnerInset: Single;
    LoadingSpinnerThickness: Single;
    LoadingDotsRadius: Single;
    LoadingDotsSpacing: Single;
    LoadingDotsInactiveAlpha: Byte;
    LoadingSpinnerTrackAlpha: Byte;
    LoadingDisabledAlpha: Byte;
    LoadingSkeletonAvatarTop: Single;
    LoadingSkeletonAvatarWidth: Single;
    LoadingSkeletonAvatarHeight: Single;
    LoadingSkeletonAvatarRadius: Single;
    LoadingSkeletonTextLeft: Single;
    LoadingSkeletonTitleTop: Single;
    LoadingSkeletonTitleHeight: Single;
    LoadingSkeletonLineTop: Single;
    LoadingSkeletonLineRightInset: Single;
    LoadingSkeletonLineHeight: Single;
    LoadingSkeletonRadius: Single;
    LoadingSkeletonHighlightWidth: Single;
    LoadingSkeletonHighlightAlpha: Byte;
    PaginationRadius: Single;
    PaginationBorderWidth: Single;
    PaginationButtonSize: Single;
    PaginationGap: Single;
    PaginationPageSizeGap: Single;
    PaginationComboWidth: Single;
    PaginationComboVerticalOffset: Single;
    PaginationComboHeightOffset: Single;
    PaginationIconSize: Single;
    ToastRadius: Single;
    ToastBorderWidth: Single;
    ToastBorderAlpha: Byte;
    ToastIndicatorX: Single;
    ToastIndicatorRadius: Single;
    ToastTitleX: Single;
    ToastTitleBaseline: Single;
    ToastMessageBaseline: Single;
    ToastTitleTextSize: Single;
    ToastMessageTextSize: Single;
    ToastTextRightInset: Single;
    TooltipRadius: Single;
    TooltipBorderWidth: Single;
    TooltipBackgroundAlpha: Byte;
    TooltipBorderAlpha: Byte;
    TooltipTextInsetHorizontal: Single;
    TooltipTextInsetVertical: Single;
    TooltipTextSize: Single;
    TooltipOffset: Single;
    ContainerRadius: Single;
    ContainerBorderWidth: Single;
    ContainerPadding: Single;
    ContainerDarkPanelRadius: Single;
    ContainerDarkPanelPadding: Single;
    ContainerDarkCardRadius: Single;
    ContainerDarkCardPadding: Single;
    ContainerHeaderHeight: Single;
    ContainerTitleTopOffset: Single;
    ContainerTitleHeight: Single;
    ContainerSubtitleTopOffset: Single;
    ContainerSubtitleHeight: Single;
    GridContainerRadius: Single;
    GridContainerBorderWidth: Single;
    GridContainerGutter: Single;
    GridContainerPadding: Single;
    GridContainerRowHeight: Single;
    GridContainerDenseRadius: Single;
    GridContainerDenseGutter: Single;
    GridContainerDensePadding: Single;
    GridContainerDenseRowHeight: Single;
    GridContainerCompactRadius: Single;
    GridContainerCompactGutter: Single;
    GridContainerCompactPadding: Single;
    GridContainerCompactRowHeight: Single;
    GridContainerActionTilesRadius: Single;
    GridContainerActionTilesGutter: Single;
    GridContainerActionTilesPadding: Single;
    GridContainerActionTilesRowHeight: Single;
    SummaryCardRadius: Single;
    SummaryCardDashboardRadius: Single;
    SummaryCardPadding: Single;
    SummaryCardBadgeSize: Single;
    SummaryCardIconInset: Single;
    SummaryCardTextGap: Single;
    SummaryCardTitleBaseline: Single;
    SummaryCardValueBaseline: Single;
    SummaryCardFooterInset: Single;
    SummaryCardTitleTextSize: Single;
    SummaryCardValueTextSize: Single;
    SummaryCardFooterTextSize: Single;
    SummaryCardDisabledAlpha: Byte;
    SummaryCardBorderAlpha: Byte;
    SummaryCardBadgeAlpha: Byte;
    BadgeRadius: Single;
    BadgePadding: Single;
    BadgePillPadding: Single;
    BadgeIconSize: Single;
    BadgePillIconSize: Single;
    BadgeIconGap: Single;
    BadgeBorderAlpha: Byte;
    BadgeOutlineBorderAlpha: Byte;
    BadgeDisabledAlpha: Byte;
    BadgeCloseHoverAlpha: Byte;
    BadgeCloseInset: Single;
    SelectorToggleWidth: Single;
    SelectorToggleHeight: Single;
    SelectorToggleKnobOffset: Single;
    SelectorToggleKnobRadius: Single;
    SelectorRadioCenter: Single;
    SelectorRadioRadius: Single;
    SelectorRadioDotRadius: Single;
    SelectorCheckSize: Single;
    SelectorCheckRadius: Single;
    SelectorCheckInset: Single;
    SelectorTextOffset: Single;
    SelectorTextBaselineOffset: Single;
    SelectorTextSize: Single;
    SelectorStrokeWidth: Single;
    SelectorCheckedBorderWidth: Single;
    SelectorDisabledAlpha: Byte;
    SelectorHoverAlpha: Byte;
    SliderTrackLeft: Single;
    SliderTrackRightWithValue: Single;
    SliderTrackRightWithoutValue: Single;
    SliderTrackThickness: Single;
    SliderKnobRadius: Single;
    SliderValueRight: Single;
    SliderValueWidth: Single;
    SliderValueBaselineOffset: Single;
    SliderValueTextSize: Single;
    SliderTrackAlpha: Byte;
    SliderDisabledTrackAlpha: Byte;
    SliderDisabledAlpha: Byte;
    SliderHoverAlpha: Byte;
    ScrollContainerRadius: Single;
    ScrollContainerBorderWidth: Single;
    ScrollBarThumbRadius: Single;
    ScrollBarBorderWidth: Single;
    ScrollBarArrowStrokeWidth: Single;
    ScrollBarArrowInset: Single;
    ScrollContainerViewportRadius: Single;
    ChartRadius: Single;
    ChartBorderWidth: Single;
    ChartInsetLeft: Single;
    ChartInsetTop: Single;
    ChartInsetRight: Single;
    ChartInsetBottom: Single;
    ChartGridLines: Integer;
    ChartGridAlpha: Byte;
    ChartLineWidth: Single;
    ChartPointRadius: Single;
    ChartBarGap: Single;
    ChartBarMinWidth: Single;
    ChartBarRadius: Single;
    ChartAreaAlpha: Byte;
    ChartDoughnutThickness: Single;
    ChartDoughnutGap: Single;
    ChartDoughnutStartAngle: Single;
    ChartFullCircleDegrees: Single;
    ReportRadius: Single;
    ReportBorderWidth: Single;
    ReportToolbarHeight: Single;
    ReportPageWidth: Single;
    ReportPageTop: Single;
    ReportPageBottomInset: Single;
    ReportPageRadius: Single;
    ReportTextInset: Single;
    ReportRowHeight: Single;
    ReportRowRadius: Single;
    ReportToolbarRadius: Single;
    ReportToolbarPageX: Single;
    ReportToolbarBaseline: Single;
    ReportToolbarTextSize: Single;
    ReportToolbarPageWidth: Single;
    ReportToolbarZoomRight: Single;
    ReportToolbarZoomWidth: Single;
    ReportTitleTop: Single;
    ReportTitleTextSize: Single;
    ReportSubtitleTop: Single;
    ReportBodyTextSize: Single;
    ReportRowTop: Single;
    ReportColumnInset: Single;
    ReportValueRight: Single;
    ReportTextWidth: Single;
    ReportValueWidth: Single;
    TabsHeaderRadius: Single;
    TabsPillRadius: Single;
    TabsUnderlineRadius: Single;
    TabsUnderlineThickness: Single;
    TabsCaptionInset: Single;
    TabsFocusRadius: Single;
    TabsHeaderInset: Single;
    TabsHeaderCrossInset: Single;
    TabsUnderlineInset: Single;
    TabsVerticalMinItem: Single;
    TabsHorizontalMinItem: Single;
    TabsVerticalExtent: Single;
    TabsHorizontalExtent: Single;
    TabsItemGap: Single;
    TabsDividerWidth: Single;
    TabsIndicatorWidth: Single;
    TabsFocusWidth: Single;
    TabsContentGutter: Single;
    TabsContentInset: Single;
    TabsContentRadius: Single;
    DataGridHeaderHeight: Single;
    DataGridHeaderRadius: Single;
    DataGridRowHeight: Single;
    DataGridSmallRowHeight: Single;
    DataGridSmallHeaderHeight: Single;
    DataGridSmallTextSize: Single;
    DataGridMediumRowHeight: Single;
    DataGridMediumHeaderHeight: Single;
    DataGridMediumTextSize: Single;
    DataGridLargeRowHeight: Single;
    DataGridLargeHeaderHeight: Single;
    DataGridLargeTextSize: Single;
    DataGridRadius: Single;
    DataGridCornerRadius: Single;
    DataGridBorderWidth: Single;
    DataGridBackground: TAlphaColor;
    DataGridHeader: TAlphaColor;
    DataGridHeaderText: TAlphaColor;
    DataGridText: TAlphaColor;
    DataGridSecondaryText: TAlphaColor;
    DataGridDisabledText: TAlphaColor;
    DataGridRowAlternate: TAlphaColor;
    DataGridHover: TAlphaColor;
    DataGridFocus: TAlphaColor;
    DataGridEditing: TAlphaColor;
    DataGridSuccess: TAlphaColor;
    DataGridError: TAlphaColor;
    DataGridLoading: TAlphaColor;
    DataGridEmpty: TAlphaColor;
    DataGridRowInset: Single;
    DataGridRowRadius: Single;
    DataGridSelection: TAlphaColor;
    DataGridSelectionBorder: TAlphaColor;
    DataGridSelectionFillRadius: Single;
    DataGridHoverBorder: TAlphaColor;
    DataGridHoverInset: Single;
    DataGridHoverRadius: Single;
    DataGridHoverBorderWidth: Single;
    DataGridSelectionInset: Single;
    DataGridSelectionRadius: Single;
    DataGridSelectionBorderWidth: Single;
    DataGridBorder: TAlphaColor;
    DataGridStatusBackground: TAlphaColor;
    DataGridStatusText: TAlphaColor;
    DataGridStatusInset: Single;
    DataGridActionBackground: TAlphaColor;
    DataGridActionText: TAlphaColor;
    DataGridFooter: TAlphaColor;
    DataGridFooterBackground: TAlphaColor;
    DataGridFooterText: TAlphaColor;
    DataGridFooterInset: Single;
    DataGridFooterRadius: Single;
    DataGridFooterTextLeftInset: Single;
    DataGridFooterTextBottomInset: Single;
    DataGridFooterTextRightInset: Single;
    DataGridFooterTextSize: Single;
    DataGridFooterValueWidth: Single;
    DataGridFooterValueRightInset: Single;
    DataGridFooterValueBottomInset: Single;
    DataGridFooterValueTextSize: Single;
    DataGridFooterValueText: TAlphaColor;
    DataGridPreviewCanvasBackground: TAlphaColor;
    DataGridPreviewFrameBackground: TAlphaColor;
    DataGridPreviewFrameBorder: TAlphaColor;
    DataGridPreviewFrameInset: Single;
    DataGridPreviewFrameRadius: Single;
    DataGridPreviewFrameBorderWidth: Single;
    DataGridPreviewRowBackground: TAlphaColor;
    DataGridPreviewRowInset: Single;
    DataGridPreviewRowHeight: Single;
    DataGridPreviewRowRadius: Single;
    DataGridPreviewRowTextInset: Single;
    DataGridPreviewRowTextSize: Single;
    DataGridPreviewRowText: TAlphaColor;
    DataGridPreviewStatusBackground: TAlphaColor;
    DataGridPreviewStatusInset: Single;
    DataGridPreviewStatusTopInset: Single;
    DataGridPreviewStatusBottomInset: Single;
    DataGridPreviewStatusRadius: Single;
    DataGridPreviewStatusTextSize: Single;
    DataGridPreviewStatusText: TAlphaColor;
    DataGridPreviewHeaderInset: Single;
    DataGridPreviewHeaderHeight: Single;
    DataGridPreviewHeaderBackground: TAlphaColor;
    DataGridPreviewHeaderRadius: Single;
    DataGridPreviewHeaderTextInset: Single;
    DataGridPreviewHeaderTextSize: Single;
    DataGridPreviewHeaderText: TAlphaColor;
    DataGridPreviewRowsStart: Single;
    DataGridPreviewFooterInset: Single;
    DataGridPreviewFooterHeight: Single;
    DataGridPreviewFooterBackground: TAlphaColor;
    DataGridPreviewFooterRadius: Single;
    DataGridPreviewFooterTextLeftInset: Single;
    DataGridPreviewFooterTextBottomInset: Single;
    DataGridPreviewFooterTextSize: Single;
    DataGridPreviewFooterText: TAlphaColor;
    DataGridPreviewFooterTextMaxWidthRatio: Single;
    DataGridPreviewFooterValueLeftRatio: Single;
    DataGridPreviewFooterValueTopOffset: Single;
    DataGridPreviewFooterValueRightInset: Single;
    DataGridPreviewFooterValueBottomInset: Single;
    DataGridPreviewFooterValueTextSize: Single;
    DataGridPreviewFooterValueText: TAlphaColor;
    DataGridActionSize: Single;
    DataGridActionGap: Single;
    DataGridActionInset: Single;
    DataGridStatusRadius: Single;
    DataGridFooterHeight: Single;
    DataGridCellInset: Single;
    DataGridCellPaddingHorizontal: Single;
    DataGridCellPaddingVertical: Single;
    DataGridStateIconSize: Single;
    DataGridStateTextTopGap: Single;
    DataGridStateHorizontalInset: Single;
    DataGridTextSize: Single;
    GridTextSize: Single;
    DataGridActionDangerBackground: TAlphaColor;
    DataGridActionDangerText: TAlphaColor;
    DataGridActionRadius: Single;
    DataGridActionBorderWidth: Single;
    DataGridActionIconInset: Single;
    DateTimePickerIconSize: Single;
    DateTimePickerIconRightInset: Single;
    DateTimePickerIconColumnWidth: Single;
    DateTimePickerNativeRightPadding: Single;
    DateTimePickerNativeLeftInset: Single;
    TimeStepMinutes: Integer;
    // Shared native field caption/support anatomy. These fixed values are not
    // DPI/manual scale factors.
    FieldLabelRowHeight: Single;
    FieldLabelTextSize: Single;
    FieldRequiredGap: Single;
    FieldChromeTop: Single;
    FieldSupportGap: Single;
    FieldSupportRowHeight: Single;
    FieldSupportTextSize: Single;
    FieldLabelText: TAlphaColor;
    FieldRequiredText: TAlphaColor;
    FieldSupportText: TAlphaColor;
    FieldCounterText: TAlphaColor;
    FieldSuccessText: TAlphaColor;
    FieldWarningText: TAlphaColor;
    FieldDangerText: TAlphaColor;
    FieldDisabledText: TAlphaColor;
    // TDACEdit foundation. These are intentionally separate from the
    // generic InputSmall/Medium/Large sizes because the VCL host, native
    // editor and Skia chrome each own a different fixed visual measure.
    InputDefaultWidth: Single;
    InputDefaultHeight: Single;
    InputChromeTop: Single;
    InputSmallChromeHeight: Single;
    InputMediumChromeHeight: Single;
    InputLargeChromeHeight: Single;
    InputCompactChromeHeight: Single;
    InputSmallEditorHeight: Single;
    InputMediumEditorHeight: Single;
    InputLargeEditorHeight: Single;
    // Optical correction for the native single-line edit baseline. This is a
    // fixed design-system metric, not DPI scaling.
    InputNativeVerticalOffset: Single;
    InputSmallTextSize: Single;
    InputMediumTextSize: Single;
    InputLargeTextSize: Single;
    InputCounterMeasureTextSize: Single;
    InputBorderInset: Single;
    InputBorderWidth: Single;
    InputFocusBorderWidth: Single;
    InputUnderlineHeight: Single;
    InputNativeHorizontalPadding: Single;
    InputNativeRightReserveWithIcon: Single;
    InputIconColumnWidth: Single;
    InputIconSize: Single;
    InputIconRightInset: Single;
    InputSupportGap: Single;
    InputSupportBaseline: Single;
    InputBackgroundAlpha: Byte;
    InputIconAlpha: Byte;
    InputBorderAlphaDisabled: Byte;
    InputBorderAlphaFocus: Byte;
    InputBorderAlphaStatus: Byte;
    InputBorderAlphaHover: Byte;
    InputBorderAlphaNormal: Byte;
    InputUnderlinedBorderAlphaFocus: Byte;
    InputUnderlinedBorderAlphaHover: Byte;
    InputUnderlinedBorderAlphaNormal: Byte;
    InputChromeBackground: TAlphaColor;
    InputUnderlinedBackground: TAlphaColor;
    InputIcon: TAlphaColor;
    InputIconDisabled: TAlphaColor;
    InputLabelText: TAlphaColor;
    InputLabelRequiredText: TAlphaColor;
    InputSupportText: TAlphaColor;
    InputSupportCounterText: TAlphaColor;
    InputSuccessBorder: TAlphaColor;
    InputWarningBorder: TAlphaColor;
    InputDangerBorder: TAlphaColor;
    InputWarningSupportText: TAlphaColor;
    // TDACComboBox has a native HWND plus a Skia chrome and popup. Keep its
    // layout and semantic surfaces local so a future renderer cannot borrow
    // global/default input state while resolving FThemeMode.
    ComboBoxDefaultWidth: Single;
    ComboBoxDefaultHeight: Single;
    ComboBoxDefaultCornerRadius: Single;
    ComboBoxChromeTop: Single;
    ComboBoxSmallChromeHeight: Single;
    ComboBoxMediumChromeHeight: Single;
    ComboBoxLargeChromeHeight: Single;
    ComboBoxSmallEditorHeight: Single;
    ComboBoxMediumEditorHeight: Single;
    ComboBoxLargeEditorHeight: Single;
    ComboBoxSmallTextSize: Single;
    ComboBoxMediumTextSize: Single;
    ComboBoxLargeTextSize: Single;
    ComboBoxBorderSnapScale: Single;
    ComboBoxBorderInset: Single;
    ComboBoxBorderWidth: Single;
    ComboBoxFocusBorderWidth: Single;
    ComboBoxUnderlineHeight: Single;
    ComboBoxNativeHorizontalPadding: Single;
    ComboBoxNativeRightReserve: Single;
    ComboBoxNativeVerticalClipInset: Single;
    ComboBoxTextLeftInset: Single;
    ComboBoxTextRightReserve: Single;
    ComboBoxIconColumnWidth: Single;
    ComboBoxIconSize: Single;
    ComboBoxIconRightInset: Single;
    ComboBoxHelperExtraHeight: Single;
    ComboBoxHelperBaseline: Single;
    ComboBoxCounterMeasureTextSize: Single;
    ComboBoxPopupOffset: Single;
    ComboBoxPopupItemHeight: Single;
    ComboBoxPopupSnapScale: Single;
    ComboBoxPopupBorderInset: Single;
    ComboBoxPopupBorderWidth: Single;
    ComboBoxPopupItemInset: Single;
    ComboBoxPopupItemTextLeftInset: Single;
    ComboBoxPopupItemTextRightReserve: Single;
    ComboBoxPopupItemTextSize: Single;
    ComboBoxPopupCheckColumnWidth: Single;
    ComboBoxPopupCheckSize: Single;
    ComboBoxPopupCheckRightInset: Single;
    ComboBoxPopupSeparatorInset: Single;
    ComboBoxPopupSeparatorHeight: Single;
    ComboBoxPopupRowRadius: Single;
    ComboBoxBackgroundAlpha: Byte;
    ComboBoxIconAlpha: Byte;
    ComboBoxBorderAlphaDisabled: Byte;
    ComboBoxBorderAlphaFocus: Byte;
    ComboBoxBorderAlphaStatus: Byte;
    ComboBoxBorderAlphaHover: Byte;
    ComboBoxBorderAlphaNormal: Byte;
    ComboBoxUnderlinedBorderAlphaFocus: Byte;
    ComboBoxUnderlinedBorderAlphaHover: Byte;
    ComboBoxUnderlinedBorderAlphaNormal: Byte;
    ComboBoxPopupBackgroundAlpha: Byte;
    ComboBoxPopupBorderAlpha: Byte;
    ComboBoxPopupSelectedAlpha: Byte;
    ComboBoxPopupHotAlpha: Byte;
    ComboBoxPopupCheckAlpha: Byte;
    ComboBoxPopupSeparatorAlpha: Byte;
    ComboBoxChromeBackground: TAlphaColor;
    ComboBoxBackground: TAlphaColor;
    ComboBoxUnderlinedBackground: TAlphaColor;
    ComboBoxDisabledBackground: TAlphaColor;
    ComboBoxBorder: TAlphaColor;
    ComboBoxBorderHover: TAlphaColor;
    ComboBoxFocusBorder: TAlphaColor;
    ComboBoxSuccessBorder: TAlphaColor;
    ComboBoxWarningBorder: TAlphaColor;
    ComboBoxDangerBorder: TAlphaColor;
    ComboBoxText: TAlphaColor;
    ComboBoxDisabledText: TAlphaColor;
    ComboBoxLabelText: TAlphaColor;
    ComboBoxHelperText: TAlphaColor;
    ComboBoxWarningHelperText: TAlphaColor;
    ComboBoxCounterText: TAlphaColor;
    ComboBoxIcon: TAlphaColor;
    ComboBoxIconDisabled: TAlphaColor;
    ComboBoxPopupBackground: TAlphaColor;
    ComboBoxPopupCanvasBackground: TAlphaColor;
    ComboBoxPopupBorder: TAlphaColor;
    ComboBoxPopupItemText: TAlphaColor;
    ComboBoxPopupItemSelectedText: TAlphaColor;
    ComboBoxPopupItemSelectedBackground: TAlphaColor;
    ComboBoxPopupItemHotBackground: TAlphaColor;
    ComboBoxPopupCheck: TAlphaColor;
    ComboBoxPopupSeparator: TAlphaColor;
    // TDACDateTimePicker and its owned Skia popup. These mirror every visual
    // measurement/surface in the current field, calendar and time picker.
    DateTimeDefaultWidth: Single;
    DateTimeDefaultHeight: Single;
    DateTimeDefaultCornerRadius: Single;
    DateTimeChromeTop: Single;
    DateTimeChromeHeight: Single;
    DateTimeEditorHeight: Single;
    DateTimeTextSize: Single;
    DateTimeBorderSnapScale: Single;
    DateTimeBorderInset: Single;
    DateTimeBorderWidth: Single;
    DateTimeFocusBorderWidth: Single;
    DateTimeBorderAlphaNormal: Byte;
    DateTimeBorderAlphaFocus: Byte;
    DateTimeBorderAlphaDisabled: Byte;
    DateTimeBackgroundAlpha: Byte;
    DateTimeIconAlpha: Byte;
    DateTimeNativeHorizontalPadding: Single;
    DateTimeNativeLeftInset: Single;
    DateTimeNativeRightPadding: Single;
    DateTimeNativeDropdownClipWidth: Single;
    DateTimeNativeVerticalClipInset: Single;
    DateTimeIconColumnWidth: Single;
    DateTimeIconSize: Single;
    DateTimeIconRightInset: Single;
    DateTimeTimeStepMinutes: Integer;
    DateTimeChromeBackground: TAlphaColor;
    DateTimeBackground: TAlphaColor;
    DateTimeDisabledBackground: TAlphaColor;
    DateTimeBorder: TAlphaColor;
    DateTimeBorderHover: TAlphaColor;
    DateTimeFocusBorder: TAlphaColor;
    DateTimeSuccessBorder: TAlphaColor;
    DateTimeWarningBorder: TAlphaColor;
    DateTimeDangerBorder: TAlphaColor;
    DateTimeText: TAlphaColor;
    DateTimeDisabledText: TAlphaColor;
    DateTimeLabelText: TAlphaColor;
    DateTimeIcon: TAlphaColor;
    DateTimeIconDisabled: TAlphaColor;
    DateTimePopupWidth: Single;
    DateTimePopupCalendarHeight: Single;
    DateTimePopupTimeHeight: Single;
    DateTimePopupOffset: Single;
    DateTimePopupSnapScale: Single;
    DateTimePopupInset: Single;
    DateTimePopupRadius: Single;
    DateTimePopupBorderWidth: Single;
    DateTimePopupBackgroundAlpha: Byte;
    DateTimePopupBorderAlpha: Byte;
    DateTimePopupHeaderHeight: Single;
    DateTimePopupHeaderGap: Single;
    DateTimePopupNavigationSize: Single;
    DateTimePopupWeekHeaderHeight: Single;
    DateTimePopupWeekTopGap: Single;
    DateTimePopupWeekColumns: Integer;
    DateTimePopupCalendarTopGap: Single;
    DateTimePopupCalendarCellHeight: Single;
    DateTimePopupDayRadius: Single;
    DateTimePopupTodayBorderWidth: Single;
    DateTimePopupFooterHeight: Single;
    DateTimePopupFooterActionWidth: Single;
    DateTimePopupFooterActionGap: Single;
    DateTimePopupCaptionTextSize: Single;
    DateTimePopupBodyTextSize: Single;
    DateTimePopupTimeCaptionOffset: Single;
    DateTimePopupTimeValueTopOffset: Single;
    DateTimePopupTimeValueHeight: Single;
    DateTimePopupTimeTextSize: Single;
    DateTimePopupTimeActionTop: Single;
    DateTimePopupTimeActionHeight: Single;
    DateTimePopupTimeActionInset: Single;
    DateTimePopupTimeActionGap: Single;
    DateTimePopupTimeHitPadding: Single;
    DateTimePopupSelectedAlpha: Byte;
    DateTimePopupTodayAlpha: Byte;
    DateTimePopupActionAlpha: Byte;
    DateTimePopupBackground: TAlphaColor;
    DateTimePopupCanvasBackground: TAlphaColor;
    DateTimePopupBorder: TAlphaColor;
    DateTimePopupHeaderText: TAlphaColor;
    DateTimePopupWeekText: TAlphaColor;
    DateTimePopupDayText: TAlphaColor;
    DateTimePopupDayDisabledText: TAlphaColor;
    DateTimePopupSelectedBackground: TAlphaColor;
    DateTimePopupSelectedText: TAlphaColor;
    DateTimePopupTodayBorder: TAlphaColor;
    DateTimePopupTimeValue: TAlphaColor;
    DateTimePopupActionText: TAlphaColor;
    DateTimePopupActionSecondaryText: TAlphaColor;
    DateTimePopupAcceptBackground: TAlphaColor;
    DateTimePopupAcceptText: TAlphaColor;
    InputBackground: TAlphaColor;
    InputDisabledBackground: TAlphaColor;
    InputBorder: TAlphaColor;
    InputBorderHover: TAlphaColor;
    InputFocus: TAlphaColor;
    InputText: TAlphaColor;
    InputPlaceholder: TAlphaColor;
    InputHelper: TAlphaColor;
    InputDisabledText: TAlphaColor;
    SystemTextPrimary: TAlphaColor;
    SystemTextSecondary: TAlphaColor;
    SystemTextMuted: TAlphaColor;
    SystemTextAccent: TAlphaColor;
    SystemTextSuccess: TAlphaColor;
    SystemTextWarning: TAlphaColor;
    SystemTextDanger: TAlphaColor;
    MemoChromeBackground: TAlphaColor;
    MemoBackground: TAlphaColor;
    MemoDisabledBackground: TAlphaColor;
    MemoReadOnlyBackground: TAlphaColor;
    MemoText: TAlphaColor;
    MemoDisabledText: TAlphaColor;
    MemoReadOnlyText: TAlphaColor;
    MemoLabelText: TAlphaColor;
    MemoLabelRequiredText: TAlphaColor;
    MemoBorder: TAlphaColor;
    MemoBorderHover: TAlphaColor;
    MemoFocusBorder: TAlphaColor;
    MemoSuccessBorder: TAlphaColor;
    MemoWarningBorder: TAlphaColor;
    MemoDangerBorder: TAlphaColor;
    MemoDefaultWidth: Single;
    MemoDefaultHeight: Single;
    MemoLabeledMinimumHeight: Single;
    MemoCornerRadius: Single;
    MemoLabelHeight: Single;
    MemoLabelBaseline: Single;
    MemoLabelTextSize: Single;
    MemoPadding: Single;
    MemoTextSize: Single;
    MemoBorderInset: Single;
    MemoBackgroundAlpha: Byte;
    MemoBorderAlphaDisabled: Byte;
    MemoBorderAlphaFocus: Byte;
    MemoBorderAlphaStatus: Byte;
    MemoBorderAlphaHover: Byte;
    MemoBorderAlphaNormal: Byte;
    MemoBorderWidth: Single;
    MemoFocusBorderWidth: Single;
    Success: TAlphaColor;
    Error: TAlphaColor;
    ButtonPrimary: TAlphaColor;
    ButtonPrimaryHover: TAlphaColor;
    ButtonPrimaryPressed: TAlphaColor;
    ButtonSecondary: TAlphaColor;
    ButtonGhostHover: TAlphaColor;
    ButtonTonal: TAlphaColor;
    ButtonTonalText: TAlphaColor;
    ButtonDanger: TAlphaColor;
    ButtonSuccess: TAlphaColor;
    PopupBackground: TAlphaColor;
    PopupBorder: TAlphaColor;
    StatusBackground: TAlphaColor;
    StatusBorder: TAlphaColor;
    StatusIndicator: TAlphaColor;
    StatusText: TAlphaColor;
    StatusTextSecondary: TAlphaColor;
    ProgressTrack: TAlphaColor;
    ProgressValueText: TAlphaColor;
    ProgressWarning: TAlphaColor;
    ProgressDanger: TAlphaColor;
    ProgressInfo: TAlphaColor;
    ProgressNeutral: TAlphaColor;
    LoadingSpinnerTrack: TAlphaColor;
    LoadingAccent: TAlphaColor;
    LoadingSkeletonBase: TAlphaColor;
    LoadingSkeletonHighlight: TAlphaColor;
    PaginationBackground: TAlphaColor;
    PaginationBorder: TAlphaColor;
    ToastSuccessBackground: TAlphaColor;
    ToastWarningBackground: TAlphaColor;
    ToastDangerBackground: TAlphaColor;
    ToastInfoBackground: TAlphaColor;
    ToastNeutralBackground: TAlphaColor;
    ToastSuccessBorder: TAlphaColor;
    ToastWarningBorder: TAlphaColor;
    ToastDangerBorder: TAlphaColor;
    ToastInfoBorder: TAlphaColor;
    ToastNeutralBorder: TAlphaColor;
    FeedbackText: TAlphaColor;
    TooltipBackground: TAlphaColor;
    TooltipBorder: TAlphaColor;
    TooltipText: TAlphaColor;
    ContainerSuiteBackground: TAlphaColor;
    ContainerSuiteBorder: TAlphaColor;
    ContainerDarkBackground: TAlphaColor;
    ContainerDarkBorder: TAlphaColor;
    ContainerDarkCardBackground: TAlphaColor;
    ContainerDarkCardBorder: TAlphaColor;
    ContainerDarkTitle: TAlphaColor;
    ContainerDarkSubtitle: TAlphaColor;
    ContainerTitle: TAlphaColor;
    ContainerSubtitle: TAlphaColor;
    TabsSurface: TAlphaColor;
    TabsDivider: TAlphaColor;
    TabsTextDefault: TAlphaColor;
    TabsTextHover: TAlphaColor;
    TabsTextActive: TAlphaColor;
    TabsTextDisabled: TAlphaColor;
    TabsHoverBackground: TAlphaColor;
    TabsActiveBackground: TAlphaColor;
    TabsIndicator: TAlphaColor;
    TabsFocus: TAlphaColor;
    GridContainerBackground: TAlphaColor;
    GridContainerBorder: TAlphaColor;
    GridContainerTransparentBackground: TAlphaColor;
    GridContainerTransparentBorder: TAlphaColor;
    SummaryCardBackground: TAlphaColor;
    SummaryCardBorder: TAlphaColor;
    SummaryCardDashboardBackground: TAlphaColor;
    SummaryCardDashboardBorder: TAlphaColor;
    SummaryCardSuccess: TAlphaColor;
    SummaryCardTitle: TAlphaColor;
    SummaryCardText: TAlphaColor;
    SummaryCardFooterNeutral: TAlphaColor;
    SummaryCardWarning: TAlphaColor;
    SummaryCardDanger: TAlphaColor;
    BadgeSoftBackground: TAlphaColor;
    BadgeOutlineBackground: TAlphaColor;
    BadgeBorder: TAlphaColor;
    BadgeText: TAlphaColor;
    SelectorTrack: TAlphaColor;
    SelectorTrackHover: TAlphaColor;
    SelectorControlBackground: TAlphaColor;
    SelectorBorder: TAlphaColor;
    SelectorText: TAlphaColor;
    SelectorDisabledText: TAlphaColor;
    SelectorKnob: TAlphaColor;
    SliderTrack: TAlphaColor;
    SliderText: TAlphaColor;
    ScrollContainerBackground: TAlphaColor;
    ScrollContainerBorder: TAlphaColor;
    ScrollContainerViewportBackground: TAlphaColor;
    ScrollContainerViewportBorder: TAlphaColor;
    ScrollBarTrack: TAlphaColor;
    ScrollBarThumb: TAlphaColor;
    ScrollBarThumbHot: TAlphaColor;
    ScrollBarThumbPressed: TAlphaColor;
    ScrollBarArrow: TAlphaColor;
    ScrollBarBorder: TAlphaColor;
    ChartAccent: TAlphaColor;
    ChartAccentStrong: TAlphaColor;
    ChartGrid: TAlphaColor;
    ChartDashboardBackground: TAlphaColor;
    ChartDashboardBorder: TAlphaColor;
    class function Dark: TDACControlTokens; static;
    class function Light: TDACControlTokens; static;
  end;

implementation

uses
  DAC.Components.DesignSystem.OpacityTokens,
  DAC.Components.DesignSystem.SpacingTokens,
  DAC.Components.DesignSystem.ControlTokens.Field,
  DAC.Components.DesignSystem.ControlTokens.Button,
  DAC.Components.DesignSystem.ControlTokens.Selector,
  DAC.Components.DesignSystem.ControlTokens.Tab,
  DAC.Components.DesignSystem.ControlTokens.Chart,
  DAC.Components.DesignSystem.ControlTokens.Feedback,
  DAC.Components.DesignSystem.ControlTokens.Layout;

procedure ConfigureMetrics(var AValue: TDACControlTokens);
var
  LSpacing: TDACSpacingTokens;
begin
  LSpacing := TDACSpacingTokens.Default;
  AValue.AlphaOpaque := DACOpacityOpaque;
  AValue.BadgeDefaultWidth := 92;
  AValue.BadgeDefaultHeight := 28;
  AValue.ChartDefaultWidth := 260;
  AValue.ChartDefaultHeight := 170;
  AValue.ContainerDefaultWidth := 460;
  AValue.ContainerDefaultHeight := 200;
  AValue.DataGridDefaultWidth := 760;
  AValue.DataGridDefaultHeight := 170;
  AValue.ToastDefaultWidth := 260;
  AValue.ToastDefaultHeight := 72;
  AValue.ModalDefaultWidth := 320;
  AValue.ModalDefaultHeight := 180;
  AValue.TooltipDefaultWidth := 220;
  AValue.TooltipDefaultHeight := 36;
  AValue.GridContainerDefaultWidth := 640;
  AValue.GridContainerDefaultHeight := 320;
  AValue.GridContainerDefaultColumns := 12;
  AValue.GridContainerMinimumChildWidth := 48;
  AValue.GridContainerMinimumRowHeight := 24;
  AValue.ComboBoxDefaultDropDownCount := 8;
  AValue.LoadingDefaultWidth := 160;
  AValue.LoadingDefaultHeight := 48;
  AValue.PaginationDefaultWidth := 520;
  AValue.PaginationDefaultHeight := 40;
  AValue.PaginationDefaultPageCount := 5;
  AValue.PaginationDefaultPageIndex := 1;
  AValue.PaginationDefaultPageSize := 10;
  AValue.PaginationVisiblePageButtonCount := 5;
  AValue.ProgressDefaultWidth := 260;
  AValue.ProgressDefaultHeight := 28;
  AValue.ReportViewerDefaultWidth := 720;
  AValue.ReportViewerDefaultHeight := 360;
  AValue.ScrollContainerDefaultWidth := 360;
  AValue.ScrollContainerDefaultHeight := 220;
  AValue.SelectorDefaultWidth := 180;
  AValue.SelectorDefaultHeight := 28;
  AValue.ToggleDefaultWidth := 190;
  AValue.ToggleDefaultHeight := 30;
  AValue.SliderDefaultWidth := 260;
  AValue.SliderDefaultHeight := 36;
  AValue.SkiaControlDefaultWidth := 280;
  AValue.SkiaControlDefaultHeight := 160;
  AValue.StatusBarDefaultWidth := 620;
  AValue.SummaryCardDefaultWidth := 150;
  AValue.SummaryCardDefaultHeight := 116;
  AValue.TabsDefaultWidth := 420;
  AValue.TabsDefaultHeight := 180;
  AValue.TabsSmall.Height := 32;
  AValue.TabsSmall.PaddingHorizontal := 12;
  AValue.TabsSmall.PaddingVertical := 6;
  AValue.TabsSmall.IconSize := 16;
  AValue.TabsSmall.TextSize := 12;
  AValue.TabsSmall.NativeFontSize := 7.5;
  AValue.TabsMedium.Height := 40;
  AValue.TabsMedium.PaddingHorizontal := 16;
  AValue.TabsMedium.PaddingVertical := 8;
  AValue.TabsMedium.IconSize := 18;
  AValue.TabsMedium.TextSize := 14;
  AValue.TabsMedium.NativeFontSize := 8;
  AValue.TabsLarge.Height := 48;
  AValue.TabsLarge.PaddingHorizontal := 20;
  AValue.TabsLarge.PaddingVertical := 10;
  AValue.TabsLarge.IconSize := 20;
  AValue.TabsLarge.TextSize := 16;
  AValue.TabsLarge.NativeFontSize := 9;
  AValue.ButtonSmall.Height := 32;
  AValue.ButtonSmall.PaddingHorizontal := 12;
  AValue.ButtonSmall.PaddingVertical := 6;
  AValue.ButtonSmall.IconSize := 16;
  AValue.ButtonSmall.TextSize := 13;
  AValue.ButtonSmall.NativeFontSize := 7.5;
  AValue.ButtonMedium.Height := 40;
  AValue.ButtonMedium.PaddingHorizontal := 16;
  AValue.ButtonMedium.PaddingVertical := 10;
  AValue.ButtonMedium.IconSize := 18;
  AValue.ButtonMedium.TextSize := 14;
  AValue.ButtonMedium.NativeFontSize := 8;
  AValue.ButtonLarge.Height := 48;
  AValue.ButtonLarge.PaddingHorizontal := 20;
  AValue.ButtonLarge.PaddingVertical := 14;
  AValue.ButtonLarge.IconSize := 20;
  AValue.ButtonLarge.TextSize := 15;
  AValue.ButtonCompactCornerRadius := 4;
  AValue.ButtonRoundedCornerRadius := 12;
  AValue.ButtonLarge.NativeFontSize := 9;
  AValue.ButtonDefaultWidth := 128;
  AValue.ButtonDefaultHeight := 36;
  AValue.ButtonDefaultCornerRadius := DACButtonDefaultCornerRadius;
  AValue.ButtonMaximumIconSize := 64;
  AValue.ButtonContentGap := 8;
  AValue.ButtonMinimumWidth := 44;
  AValue.ButtonPainterSnapScale := 1;
  AValue.ButtonPainterInset := 0.5;
  AValue.ButtonBorderWidth := 1;
  AValue.ButtonInputActionDividerWidth := 1;
  AValue.ButtonInputActionDividerVerticalInset := 1;
  AValue.ButtonInputActionCaptionTextSize := 11;
  AValue.ButtonInputActionCaptionRightInset := 8;
  AValue.ButtonCaptionBold := True;
  AValue.ButtonCaptionMaxLines := 1;
  AValue.ButtonAlphaOpaque := DACOpacityOpaque;
  AValue.ButtonBorderAlphaNone := DACOpacityTransparent;
  AValue.ButtonBorderAlphaGhostNormal := 140;
  AValue.ButtonBorderAlphaGhostActive := 190;
  AValue.ButtonBorderAlphaFull := DACOpacityOpaque;
  AValue.ButtonEditDefaultWidth := 300;
  AValue.ButtonEditDefaultButtonWidth := DACButtonEditDefaultButtonWidth;
  AValue.ButtonEditDefaultCornerRadius := DACButtonEditDefaultCornerRadius;
  AValue.ButtonEditButtonCornerRadius := 0;
  AValue.ButtonEditButtonGap := 0;
  // Preserve the outer TDACEdit border around the opaque action child.
  AValue.ButtonEditButtonInset := 1;
  AValue.InputSmall := AValue.ButtonSmall;
  AValue.InputMedium := AValue.ButtonMedium;
  AValue.InputLarge := AValue.ButtonLarge;
  AValue.BorderWidth := 1;
  AValue.FocusRingWidth := 2;
  AValue.ButtonRadius := 12;
  AValue.InputRadius := DACEditDefaultCornerRadius;
  AValue.ComboBoxRadius := 8;
  AValue.DateTimePickerRadius := 8;
  AValue.IconGap := 8;
  AValue.ButtonEditDividerWidth := 1;
  AValue.DropDownItemHeight := 40;
  AValue.PopupRadius := 8;
  AValue.PopupWidth := 320;
  AValue.PopupCalendarHeight := 336;
  AValue.PopupTimeHeight := 248;
  AValue.PopupOuterInset := 12;
  AValue.PopupHeaderHeight := 44;
  AValue.PopupNavigationSize := 32;
  AValue.PopupWeekHeaderHeight := 24;
  AValue.PopupCalendarCellHeight := 34;
  AValue.PopupDayRadius := 17;
  AValue.PopupFooterHeight := 36;
  AValue.PopupFooterActionWidth := 60;
  AValue.PopupOffset := 4;
  AValue.PopupHeaderGap := 4;
  AValue.PopupWeekTopGap := 8;
  AValue.PopupCalendarTopGap := 10;
  AValue.PopupTimeCaptionOffset := 6;
  AValue.PopupTimeValueTopOffset := 16;
  AValue.PopupTimeValueHeight := 80;
  AValue.PopupTimeActionInset := 10;
  AValue.PopupTimeActionGap := 6;
  AValue.PopupTimeHitPadding := 8;
  AValue.PopupWeekColumns := 7;
  AValue.PopupTimeActionTop := 158;
  AValue.PopupTimeActionHeight := 44;
  AValue.PopupCaptionTextSize := 14;
  AValue.PopupBodyTextSize := 12;
  AValue.PopupTimeTextSize := 32;
  AValue.StatusBarHeight := 34;
  AValue.StatusBarInset := 16;
  AValue.StatusBarRadius := 0;
  AValue.StatusBarIndicatorRadius := 4;
  AValue.StatusBarTextSize := 11;
  AValue.StatusBarTextBaseline := 22;
  AValue.StatusBarLeftTextOffset := 12;
  AValue.StatusBarRightTextInset := 16;
  AValue.ProgressLinearThickness := 8;
  AValue.ProgressCircularThickness := 8;
  AValue.ProgressValueTextSize := 9;
  AValue.ProgressValueTextInset := 36;
  AValue.ProgressValueTextOffset := 4;
  AValue.ProgressDisabledAlpha := 120;
  AValue.LoadingTimerInterval := 120;
  AValue.LoadingSpinnerInset := 8;
  AValue.LoadingSpinnerThickness := 4;
  AValue.LoadingDotsRadius := 5;
  AValue.LoadingDotsSpacing := 20;
  AValue.LoadingDotsInactiveAlpha := 92;
  AValue.LoadingSpinnerTrackAlpha := 100;
  AValue.LoadingDisabledAlpha := 120;
  AValue.LoadingSkeletonAvatarTop := 6;
  AValue.LoadingSkeletonAvatarWidth := 56;
  AValue.LoadingSkeletonAvatarHeight := 32;
  AValue.LoadingSkeletonAvatarRadius := 6;
  AValue.LoadingSkeletonTextLeft := 66;
  AValue.LoadingSkeletonTitleTop := 10;
  AValue.LoadingSkeletonTitleHeight := 8;
  AValue.LoadingSkeletonLineTop := 28;
  AValue.LoadingSkeletonLineRightInset := 24;
  AValue.LoadingSkeletonLineHeight := 8;
  AValue.LoadingSkeletonRadius := 4;
  AValue.LoadingSkeletonHighlightWidth := 44;
  AValue.LoadingSkeletonHighlightAlpha := 150;
  AValue.PaginationRadius := 8;
  AValue.PaginationBorderWidth := 1;
  AValue.PaginationButtonSize := 32;
  AValue.PaginationGap := 8;
  AValue.PaginationPageSizeGap := 16;
  AValue.PaginationComboWidth := 132;
  AValue.PaginationComboVerticalOffset := 2;
  AValue.PaginationComboHeightOffset := 4;
  AValue.PaginationIconSize := 14;
  AValue.ToastRadius := 8;
  AValue.ToastBorderWidth := 1;
  AValue.ToastBorderAlpha := 150;
  AValue.ToastIndicatorX := 24;
  AValue.ToastIndicatorRadius := 9;
  AValue.ToastTitleX := 46;
  AValue.ToastTitleBaseline := 30;
  AValue.ToastMessageBaseline := 50;
  AValue.ToastTitleTextSize := 12;
  AValue.ToastMessageTextSize := 11;
  AValue.ToastTextRightInset := 58;
  AValue.TooltipRadius := 6;
  AValue.TooltipBorderWidth := 1;
  AValue.TooltipBackgroundAlpha := 245;
  AValue.TooltipBorderAlpha := 190;
  AValue.TooltipTextInsetHorizontal := 10;
  AValue.TooltipTextInsetVertical := 4;
  AValue.TooltipTextSize := 10;
  AValue.TooltipOffset := 4;
  AValue.ContainerRadius := DACContainerDefaultRadius;
  AValue.ContainerBorderWidth := DACContainerDefaultBorderWidth;
  AValue.ContainerPadding := DACContainerDefaultPadding;
  AValue.ContainerDarkPanelRadius := 14;
  AValue.ContainerDarkPanelPadding := 20;
  AValue.ContainerDarkCardRadius := 12;
  AValue.ContainerDarkCardPadding := 12;
  AValue.ContainerHeaderHeight := DACContainerDefaultHeaderHeight;
  AValue.ContainerTitleTopOffset := 5;
  AValue.ContainerTitleHeight := 20;
  AValue.ContainerSubtitleTopOffset := 29;
  AValue.ContainerSubtitleHeight := 17;
  AValue.GridContainerRadius := DACGridContainerDefaultRadius;
  AValue.GridContainerBorderWidth := 1;
  AValue.GridContainerGutter := DACGridContainerDefaultGutter;
  AValue.GridContainerPadding := DACGridContainerDefaultPadding;
  AValue.GridContainerRowHeight := DACGridContainerDefaultRowHeight;
  AValue.GridContainerDenseRadius := 10;
  AValue.GridContainerDenseGutter := 10;
  AValue.GridContainerDensePadding := 16;
  AValue.GridContainerDenseRowHeight := 44;
  AValue.GridContainerCompactRadius := 10;
  AValue.GridContainerCompactGutter := 10;
  AValue.GridContainerCompactPadding := 16;
  AValue.GridContainerCompactRowHeight := 46;
  AValue.GridContainerActionTilesRadius := 0;
  AValue.GridContainerActionTilesGutter := 12;
  AValue.GridContainerActionTilesPadding := 0;
  AValue.GridContainerActionTilesRowHeight := 70;
  AValue.SummaryCardRadius := DACSummaryCardDefaultCornerRadius;
  AValue.SummaryCardDashboardRadius := 14;
  AValue.SummaryCardPadding := 12;
  AValue.SummaryCardBadgeSize := 32;
  AValue.SummaryCardIconInset := 8;
  AValue.SummaryCardTextGap := 8;
  AValue.SummaryCardTitleBaseline := 25;
  AValue.SummaryCardValueBaseline := 50;
  AValue.SummaryCardFooterInset := 20;
  AValue.SummaryCardTitleTextSize := 12;
  AValue.SummaryCardValueTextSize := 16;
  AValue.SummaryCardFooterTextSize := 12;
  AValue.SummaryCardDisabledAlpha := 130;
  AValue.SummaryCardBorderAlpha := 210;
  AValue.SummaryCardBadgeAlpha := 34;
  AValue.BadgeRadius := DACBadgeDefaultCornerRadius;
  AValue.BadgePadding := 12;
  AValue.BadgePillPadding := 16;
  AValue.BadgeIconSize := 13;
  AValue.BadgePillIconSize := 14;
  AValue.BadgeIconGap := 6;
  AValue.BadgeBorderAlpha := 170;
  AValue.BadgeOutlineBorderAlpha := 230;
  AValue.BadgeDisabledAlpha := 120;
  AValue.BadgeCloseHoverAlpha := 24;
  AValue.BadgeCloseInset := 2;
  AValue.SelectorToggleWidth := 44;
  AValue.SelectorToggleHeight := 24;
  AValue.SelectorToggleKnobOffset := 12;
  AValue.SelectorToggleKnobRadius := 9;
  AValue.SelectorRadioCenter := 10;
  AValue.SelectorRadioRadius := 8;
  AValue.SelectorRadioDotRadius := 4;
  AValue.SelectorCheckSize := 18;
  AValue.SelectorCheckRadius := 4;
  AValue.SelectorCheckInset := 2;
  AValue.SelectorTextOffset := 28;
  AValue.SelectorTextBaselineOffset := 4;
  AValue.SelectorTextSize := 10.5;
  AValue.SelectorStrokeWidth := 1;
  AValue.SelectorCheckedBorderWidth := 1.5;
  AValue.SelectorDisabledAlpha := 120;
  AValue.SelectorHoverAlpha := 180;
  AValue.SliderTrackLeft := 8;
  AValue.SliderTrackRightWithValue := 50;
  AValue.SliderTrackRightWithoutValue := 12;
  AValue.SliderTrackThickness := 3;
  AValue.SliderKnobRadius := 8;
  AValue.SliderValueRight := 40;
  AValue.SliderValueWidth := 38;
  AValue.SliderValueBaselineOffset := 4;
  AValue.SliderValueTextSize := 10;
  AValue.SliderTrackAlpha := 150;
  AValue.SliderDisabledTrackAlpha := 80;
  AValue.SliderDisabledAlpha := 120;
  AValue.SliderHoverAlpha := 220;
  AValue.ScrollContainerRadius := DACScrollContainerDefaultCornerRadius;
  AValue.ScrollContainerBorderWidth := 1;
  AValue.ScrollBarThumbRadius := 4;
  AValue.ScrollBarBorderWidth := 1;
  AValue.ScrollBarArrowStrokeWidth := 1.5;
  AValue.ScrollBarArrowInset := 5;
  AValue.ScrollContainerViewportRadius := 0;
  AValue.ChartRadius := 8; AValue.ChartBorderWidth := 1;
  AValue.ChartInsetLeft := 18; AValue.ChartInsetTop := 16;
  AValue.ChartInsetRight := 16; AValue.ChartInsetBottom := 22;
  AValue.ChartGridLines := 4; AValue.ChartGridAlpha := 130;
  AValue.ChartLineWidth := 2; AValue.ChartPointRadius := 3;
  AValue.ChartBarGap := 8; AValue.ChartBarMinWidth := 8; AValue.ChartBarRadius := 3;
  AValue.ChartAreaAlpha := 70; AValue.ChartDoughnutThickness := 16; AValue.ChartDoughnutGap := 2;
  AValue.ChartDoughnutStartAngle := -90; AValue.ChartFullCircleDegrees := 360;
  AValue.ReportRadius := 8; AValue.ReportBorderWidth := 1; AValue.ReportToolbarHeight := 42;
  AValue.ReportPageWidth := 300; AValue.ReportPageTop := 62; AValue.ReportPageBottomInset := 18;
  AValue.ReportPageRadius := 4; AValue.ReportTextInset := 24; AValue.ReportRowHeight := 24; AValue.ReportRowRadius := 0;
  AValue.ReportToolbarRadius := 8; AValue.ReportToolbarPageX := 24;
  AValue.ReportToolbarBaseline := 26; AValue.ReportToolbarTextSize := 11;
  AValue.ReportToolbarPageWidth := 80; AValue.ReportToolbarZoomRight := 72;
  AValue.ReportToolbarZoomWidth := 56; AValue.ReportTitleTop := 34;
  AValue.ReportTitleTextSize := 16; AValue.ReportSubtitleTop := 56;
  AValue.ReportBodyTextSize := 9; AValue.ReportRowTop := 86;
  AValue.ReportColumnInset := 10; AValue.ReportValueRight := 112;
  AValue.ReportTextWidth := 120; AValue.ReportValueWidth := 90;
  AValue.TabsHeaderRadius := 6; AValue.TabsPillRadius := 6;
  AValue.TabsUnderlineRadius := 0; AValue.TabsUnderlineThickness := 2;
  AValue.TabsCaptionInset := 16; AValue.TabsFocusRadius := 6;
  AValue.TabsHeaderInset := 4; AValue.TabsHeaderCrossInset := 0;
  AValue.TabsUnderlineInset := 0; AValue.TabsVerticalMinItem := 40;
  AValue.TabsHorizontalMinItem := 40; AValue.TabsVerticalExtent := 160;
  AValue.TabsHorizontalExtent := 48; AValue.TabsItemGap := 4;
  AValue.TabsDividerWidth := 1; AValue.TabsIndicatorWidth := 2;
  AValue.TabsFocusWidth := 2; AValue.TabsContentGutter := 24;
  AValue.TabsContentInset := 4;
  AValue.TabsContentRadius := DACTabsDefaultCornerRadius;
  AValue.DataGridSmallRowHeight := 32; AValue.DataGridSmallHeaderHeight := 36;
  AValue.DataGridSmallTextSize := 12;
  AValue.DataGridMediumRowHeight := 36; AValue.DataGridMediumHeaderHeight := 40;
  AValue.DataGridMediumTextSize := 13;
  AValue.DataGridLargeRowHeight := 44; AValue.DataGridLargeHeaderHeight := 44;
  AValue.DataGridLargeTextSize := 14;
  AValue.DataGridHeaderHeight := AValue.DataGridMediumHeaderHeight;
  AValue.DataGridHeaderRadius := 0;
  AValue.DataGridRowHeight := AValue.DataGridMediumRowHeight;
  AValue.DataGridRadius := 8; AValue.DataGridCornerRadius := DACDataGridDefaultCornerRadius;
  AValue.DataGridBorderWidth := 1;
  AValue.DataGridActionSize := 16; AValue.DataGridActionGap := 12;
  AValue.DataGridActionInset := 6; AValue.DataGridStatusRadius := 12;
  AValue.DataGridStatusInset := 6;
  AValue.DataGridFooterHeight := 34; AValue.DataGridFooterInset := 1;
  AValue.DataGridFooterRadius := 0; AValue.DataGridFooterTextLeftInset := 14;
  AValue.DataGridFooterTextBottomInset := 12;
  AValue.DataGridFooterTextRightInset := 24;
  AValue.DataGridFooterTextSize := 12;
  AValue.DataGridFooterValueWidth := 120;
  AValue.DataGridFooterValueRightInset := 14;
  AValue.DataGridFooterValueBottomInset := 2;
  AValue.DataGridFooterValueTextSize := 12;
  AValue.DataGridPreviewFrameInset := 0.5;
  AValue.DataGridPreviewFrameRadius := 8;
  AValue.DataGridPreviewFrameBorderWidth := 1;
  AValue.DataGridPreviewRowInset := 1;
  AValue.DataGridPreviewRowHeight := 40;
  AValue.DataGridPreviewRowRadius := 0;
  AValue.DataGridPreviewRowTextInset := 8;
  AValue.DataGridPreviewRowTextSize := 11;
  AValue.DataGridPreviewStatusInset := 8;
  AValue.DataGridPreviewStatusTopInset := 7;
  AValue.DataGridPreviewStatusBottomInset := 9;
  AValue.DataGridPreviewStatusRadius := 9;
  AValue.DataGridPreviewStatusTextSize := 10;
  AValue.DataGridPreviewHeaderInset := 1;
  AValue.DataGridPreviewHeaderHeight := 44;
  AValue.DataGridPreviewHeaderRadius := 8;
  AValue.DataGridPreviewHeaderTextInset := 4;
  AValue.DataGridPreviewHeaderTextSize := 11;
  AValue.DataGridPreviewRowsStart := 45;
  AValue.DataGridPreviewFooterInset := 1;
  AValue.DataGridPreviewFooterHeight := 36;
  AValue.DataGridPreviewFooterRadius := 0;
  AValue.DataGridPreviewFooterTextLeftInset := 14;
  AValue.DataGridPreviewFooterTextBottomInset := 12;
  AValue.DataGridPreviewFooterTextSize := 11;
  AValue.DataGridPreviewFooterTextMaxWidthRatio := 0.65;
  AValue.DataGridPreviewFooterValueLeftRatio := 0.7;
  AValue.DataGridPreviewFooterValueTopOffset := 34;
  AValue.DataGridPreviewFooterValueRightInset := 14;
  AValue.DataGridPreviewFooterValueBottomInset := 2;
  AValue.DataGridPreviewFooterValueTextSize := 11;
  AValue.DataGridCellInset := 12;
  AValue.DataGridCellPaddingHorizontal := 12;
  AValue.DataGridCellPaddingVertical := 8;
  AValue.DataGridStateIconSize := 24;
  AValue.DataGridStateTextTopGap := 8;
  AValue.DataGridStateHorizontalInset := 16;
  AValue.DataGridTextSize := AValue.DataGridMediumTextSize;
  AValue.GridTextSize := AValue.DataGridMediumTextSize;
  AValue.DataGridRowInset := 1; AValue.DataGridRowRadius := 0;
  AValue.DataGridSelectionFillRadius := 0;
  AValue.DataGridSelectionInset := 1; AValue.DataGridSelectionRadius := 4;
  AValue.DataGridSelectionBorderWidth := 2;
  AValue.DataGridHoverInset := 1; AValue.DataGridHoverRadius := 4;
  AValue.DataGridHoverBorderWidth := 1;
  AValue.DataGridActionRadius := 5; AValue.DataGridActionBorderWidth := 1;
  AValue.DataGridActionIconInset := 3;
  AValue.DateTimePickerIconSize := 16;
  AValue.DateTimePickerIconRightInset := 14;
  AValue.DateTimePickerIconColumnWidth := 30;
  AValue.DateTimePickerNativeRightPadding := 54;
  AValue.DateTimePickerNativeLeftInset := 2;
  { Compact field anatomy. Native text retains its own ascent/descent metrics,
    so the surrounding rows use only the design-system spacing scale: S16 for
    label/support and S4 between consecutive field regions. }
  AValue.FieldLabelRowHeight := LSpacing.S16;
  AValue.FieldLabelTextSize := 9;
  AValue.FieldRequiredGap := 3;
  AValue.FieldChromeTop := LSpacing.S16 + LSpacing.S4;
  AValue.FieldSupportGap := LSpacing.S4;
  AValue.FieldSupportRowHeight := LSpacing.S16;
  AValue.FieldSupportTextSize := 9;
  AValue.DateTimeDefaultWidth := 220;
  AValue.DateTimeDefaultCornerRadius := DACDateTimeDefaultCornerRadius;
  AValue.DateTimeChromeTop := 24;
  AValue.DateTimeTextSize := 9;
  AValue.DateTimeBorderSnapScale := 1;
  AValue.DateTimeBorderInset := 0.5;
  AValue.DateTimeBorderWidth := 1;
  AValue.DateTimeFocusBorderWidth := 2;
  AValue.DateTimeBorderAlphaNormal := 180;
  AValue.DateTimeBorderAlphaFocus := DACOpacityOpaque;
  AValue.DateTimeBorderAlphaDisabled := 100;
  AValue.DateTimeBackgroundAlpha := DACOpacityOpaque;
  AValue.DateTimeIconAlpha := DACOpacityOpaque;
  AValue.DateTimeNativeHorizontalPadding := 16;
  AValue.DateTimeNativeLeftInset := 2;
  AValue.DateTimeNativeRightPadding := 42;
  AValue.DateTimeNativeDropdownClipWidth := 24;
  AValue.DateTimeNativeVerticalClipInset := 1;
  AValue.DateTimeIconColumnWidth := 34;
  AValue.DateTimeIconSize := 18;
  AValue.DateTimeIconRightInset := 16;
  AValue.DateTimeTimeStepMinutes := 5;
  AValue.DateTimePopupWidth := 320;
  AValue.DateTimePopupCalendarHeight := 336;
  AValue.DateTimePopupTimeHeight := 248;
  AValue.DateTimePopupOffset := 4;
  AValue.DateTimePopupSnapScale := 1;
  AValue.DateTimePopupInset := 12;
  AValue.DateTimePopupRadius := 8;
  AValue.DateTimePopupBorderWidth := 1;
  AValue.DateTimePopupBackgroundAlpha := DACOpacityOpaque;
  AValue.DateTimePopupBorderAlpha := DACOpacityOpaque;
  AValue.DateTimePopupHeaderHeight := 44;
  AValue.DateTimePopupHeaderGap := 4;
  AValue.DateTimePopupNavigationSize := 32;
  AValue.DateTimePopupWeekHeaderHeight := 24;
  AValue.DateTimePopupWeekTopGap := 8;
  AValue.DateTimePopupWeekColumns := 7;
  AValue.DateTimePopupCalendarTopGap := 10;
  AValue.DateTimePopupCalendarCellHeight := 34;
  AValue.DateTimePopupDayRadius := 17;
  AValue.DateTimePopupTodayBorderWidth := 1;
  AValue.DateTimePopupFooterHeight := 36;
  AValue.DateTimePopupFooterActionWidth := 60;
  AValue.DateTimePopupFooterActionGap := 8;
  AValue.DateTimePopupCaptionTextSize := 14;
  AValue.DateTimePopupBodyTextSize := 12;
  AValue.DateTimePopupTimeCaptionOffset := 6;
  AValue.DateTimePopupTimeValueTopOffset := 16;
  AValue.DateTimePopupTimeValueHeight := 80;
  AValue.DateTimePopupTimeTextSize := 32;
  AValue.DateTimePopupTimeActionTop := 158;
  AValue.DateTimePopupTimeActionHeight := 44;
  AValue.DateTimePopupTimeActionInset := 10;
  AValue.DateTimePopupTimeActionGap := 6;
  AValue.DateTimePopupTimeHitPadding := 8;
  AValue.DateTimePopupSelectedAlpha := DACOpacityOpaque;
  AValue.DateTimePopupTodayAlpha := DACOpacityOpaque;
  AValue.DateTimePopupActionAlpha := DACOpacityOpaque;
  AValue.TimeStepMinutes := 5;
  AValue.InputDefaultWidth := 220;
  AValue.InputChromeTop := LSpacing.S20;
  { The standalone edit uses the compact 30 px density. Its native text host
    is inset independently so the Skia border remains fully visible. }
  AValue.InputSmallChromeHeight := 30;
  { The suite has one compact single-line input density. Medium and Large are
    retained as DFM-compatible enum values, but resolve to the same Small
    chrome and native editor row. }
  AValue.InputMediumChromeHeight := AValue.InputSmallChromeHeight;
  AValue.InputLargeChromeHeight := AValue.InputSmallChromeHeight;
  AValue.InputCompactChromeHeight := AValue.InputSmallChromeHeight;
  AValue.InputDefaultHeight := AValue.InputSmallChromeHeight;
  { The native Windows edit host is intentionally 22 px inside the compact
    30 px chrome. Together with the optical offset this leaves a physical
    two-pixel lower inset for the Skia border, while retaining room for the
    native caret, selection, ascenders and descenders. }
  AValue.InputSmallEditorHeight := 22;
  AValue.InputMediumEditorHeight := AValue.InputSmallEditorHeight;
  AValue.InputLargeEditorHeight := AValue.InputSmallEditorHeight;
  { Windows single-line edit/combo glyphs sit optically above the geometric
    center of their native HWND. Move the native text row by two pixels inside
    the compact chrome, while keeping the Skia border uncovered. }
  AValue.InputNativeVerticalOffset := 2;
  { ButtonEdit and DateTimePicker are one-line field variants. Keep their
    public tokens as aliases of the input contract so all native HWND hosts
    receive the same compact chrome, editor row and optical baseline. }
  AValue.ButtonEditDefaultHeight := AValue.InputDefaultHeight;
  AValue.ButtonEditLabeledMinimumHeight := AValue.InputChromeTop +
    AValue.InputDefaultHeight;
  AValue.DateTimeDefaultHeight := AValue.InputDefaultHeight;
  AValue.DateTimeChromeHeight := AValue.InputSmallChromeHeight;
  AValue.DateTimeEditorHeight := AValue.InputSmallEditorHeight;
  AValue.InputSmallTextSize := 9;
  AValue.InputMediumTextSize := AValue.InputSmallTextSize;
  AValue.InputLargeTextSize := AValue.InputSmallTextSize;
  AValue.InputCounterMeasureTextSize := 11;
  AValue.InputBorderInset := 0.5;
  AValue.InputBorderWidth := 1;
  AValue.InputFocusBorderWidth := 2;
  AValue.InputUnderlineHeight := 1;
  AValue.InputNativeHorizontalPadding := 16;
  AValue.InputNativeRightReserveWithIcon := 42;
  AValue.InputIconColumnWidth := 34;
  AValue.InputIconSize := 18;
  AValue.InputIconRightInset := 16;
  AValue.InputSupportGap := 24;
  AValue.InputSupportBaseline := 18;
  AValue.InputBackgroundAlpha := DACOpacityOpaque;
  AValue.InputIconAlpha := DACOpacityOpaque;
  AValue.InputBorderAlphaDisabled := 130;
  AValue.InputBorderAlphaFocus := DACOpacityOpaque;
  AValue.InputBorderAlphaStatus := 215;
  AValue.InputBorderAlphaHover := 210;
  AValue.InputBorderAlphaNormal := DACOpacityOpaque;
  AValue.InputUnderlinedBorderAlphaFocus := DACOpacityOpaque;
  AValue.InputUnderlinedBorderAlphaHover := 220;
  AValue.InputUnderlinedBorderAlphaNormal := 190;
  AValue.ComboBoxDefaultWidth := 220;
  AValue.ComboBoxDefaultHeight := AValue.InputDefaultHeight;
  AValue.ComboBoxDefaultCornerRadius := DACComboBoxDefaultCornerRadius;
  AValue.ComboBoxChromeTop := LSpacing.S20;
  AValue.ComboBoxSmallChromeHeight := AValue.InputSmallChromeHeight;
  AValue.ComboBoxMediumChromeHeight := AValue.ComboBoxSmallChromeHeight;
  AValue.ComboBoxLargeChromeHeight := AValue.ComboBoxSmallChromeHeight;
  { A ComboBox hosts the same native single-line text surface as TDACEdit.
    Reuse exactly its tokenized rows so both controls share the baseline and
    vertical centering contract. }
  AValue.ComboBoxSmallEditorHeight := AValue.InputSmallEditorHeight;
  AValue.ComboBoxMediumEditorHeight := AValue.InputMediumEditorHeight;
  AValue.ComboBoxLargeEditorHeight := AValue.InputLargeEditorHeight;
  AValue.ComboBoxSmallTextSize := 9;
  AValue.ComboBoxMediumTextSize := AValue.ComboBoxSmallTextSize;
  AValue.ComboBoxLargeTextSize := AValue.ComboBoxSmallTextSize;
  AValue.ComboBoxBorderSnapScale := 1;
  AValue.ComboBoxBorderInset := 0.5;
  AValue.ComboBoxBorderWidth := 1;
  AValue.ComboBoxFocusBorderWidth := 2;
  AValue.ComboBoxUnderlineHeight := 1;
  AValue.ComboBoxNativeHorizontalPadding := 16;
  AValue.ComboBoxNativeRightReserve := 42;
  { The native border is already disabled. Clipping one pixel vertically
    removed part of descenders on some Windows font rasterizers. }
  AValue.ComboBoxNativeVerticalClipInset := 0;
  AValue.ComboBoxTextLeftInset := 14;
  AValue.ComboBoxTextRightReserve := 38;
  AValue.ComboBoxIconColumnWidth := 34;
  AValue.ComboBoxIconSize := 18;
  AValue.ComboBoxIconRightInset := 16;
  AValue.ComboBoxHelperExtraHeight := 24;
  AValue.ComboBoxHelperBaseline := 18;
  AValue.ComboBoxCounterMeasureTextSize := 11;
  AValue.ComboBoxPopupOffset := 2;
  AValue.ComboBoxPopupItemHeight := 40;
  AValue.ComboBoxPopupSnapScale := 1;
  AValue.ComboBoxPopupBorderInset := 0.5;
  AValue.ComboBoxPopupBorderWidth := 1;
  AValue.ComboBoxPopupItemInset := 1;
  AValue.ComboBoxPopupItemTextLeftInset := 14;
  AValue.ComboBoxPopupItemTextRightReserve := 34;
  AValue.ComboBoxPopupItemTextSize := 13;
  AValue.ComboBoxPopupCheckColumnWidth := 28;
  AValue.ComboBoxPopupCheckSize := 16;
  AValue.ComboBoxPopupCheckRightInset := 12;
  AValue.ComboBoxPopupSeparatorInset := 12;
  AValue.ComboBoxPopupSeparatorHeight := 0.5;
  AValue.ComboBoxPopupRowRadius := 0;
  AValue.ComboBoxBackgroundAlpha := DACOpacityOpaque;
  AValue.ComboBoxIconAlpha := DACOpacityOpaque;
  AValue.ComboBoxBorderAlphaDisabled := 130;
  AValue.ComboBoxBorderAlphaFocus := DACOpacityOpaque;
  AValue.ComboBoxBorderAlphaStatus := 215;
  AValue.ComboBoxBorderAlphaHover := 210;
  AValue.ComboBoxBorderAlphaNormal := DACOpacityOpaque;
  AValue.ComboBoxUnderlinedBorderAlphaFocus := DACOpacityOpaque;
  AValue.ComboBoxUnderlinedBorderAlphaHover := 220;
  AValue.ComboBoxUnderlinedBorderAlphaNormal := 190;
  AValue.ComboBoxPopupBackgroundAlpha := DACOpacityOpaque;
  AValue.ComboBoxPopupBorderAlpha := DACOpacityOpaque;
  AValue.ComboBoxPopupSelectedAlpha := 80;
  AValue.ComboBoxPopupHotAlpha := 42;
  AValue.ComboBoxPopupCheckAlpha := DACOpacityOpaque;
  AValue.ComboBoxPopupSeparatorAlpha := 130;
  AValue.MemoDefaultWidth := 220;
  AValue.MemoDefaultHeight := 88;
  AValue.MemoLabeledMinimumHeight := 112;
  AValue.MemoCornerRadius := DACMemoDefaultCornerRadius;
  AValue.MemoLabelHeight := 24;
  AValue.MemoLabelBaseline := 15;
  AValue.MemoLabelTextSize := 8;
  AValue.MemoPadding := 8;
  AValue.MemoTextSize := 8;
  AValue.MemoBorderInset := 0.5;
  AValue.MemoBackgroundAlpha := DACOpacityOpaque;
  AValue.MemoBorderAlphaDisabled := 130;
  AValue.MemoBorderAlphaFocus := DACOpacityOpaque;
  AValue.MemoBorderAlphaStatus := 215;
  AValue.MemoBorderAlphaHover := 210;
  AValue.MemoBorderAlphaNormal := 185;
  AValue.MemoBorderWidth := 1;
  AValue.MemoFocusBorderWidth := 2;
end;

class function TDACControlTokens.Dark: TDACControlTokens;
begin
  ConfigureMetrics(Result);
  Result.TransparentSurfaceFallback := TAlphaColor($00000000);
  Result.InputBackground := TAlphaColor($FF0F1813);
  Result.InputDisabledBackground := TAlphaColor($FF0B120E);
  Result.InputBorder := TAlphaColor($FF2A3E2F);
  Result.InputBorderHover := TAlphaColor($FF3A5D41);
  Result.InputFocus := TAlphaColor($FF4CD964);
  Result.InputText := TAlphaColor($FFE6F1EA);
  Result.InputPlaceholder := TAlphaColor($FF9AA790);
  Result.InputHelper := TAlphaColor($FF88A093);
  Result.InputDisabledText := TAlphaColor($FF6F7C74);
  Result.SystemTextPrimary := TAlphaColor($FFF5F8F5);
  Result.SystemTextSecondary := TAlphaColor($FFB8C1BA);
  Result.SystemTextMuted := TAlphaColor($FF87928A);
  Result.SystemTextAccent := TAlphaColor($FF62CC3A);
  Result.SystemTextSuccess := TAlphaColor($FF43B72B);
  Result.SystemTextWarning := TAlphaColor($FFF5C842);
  Result.SystemTextDanger := TAlphaColor($FFFF6B6B);
  Result.Success := TAlphaColor($FF4CD964);
  Result.Error := TAlphaColor($FFFF5E5E);
  Result.ButtonPrimary := TAlphaColor($FF4DAA33);
  Result.ButtonPrimaryHover := TAlphaColor($FF43982D);
  Result.ButtonPrimaryPressed := TAlphaColor($FF367A23);
  Result.ButtonSecondary := TAlphaColor($FF0F1813);
  Result.ButtonGhostHover := TAlphaColor($1F4CD964);
  Result.ButtonTonal := TAlphaColor($FFDFF0D6);
  Result.ButtonTonalText := TAlphaColor($FF245B1E);
  Result.ButtonDanger := TAlphaColor($FFD9514E);
  Result.ButtonSuccess := TAlphaColor($FF1F8B4C);
  Result.PopupBackground := TAlphaColor($FF102417);
  Result.PopupBorder := TAlphaColor($FF2A3E2F);
  Result.ButtonFallbackBackground := Result.InputBackground;
  Result.ButtonCanvasBackground := Result.PopupBackground;
  // The action is composed over the TDACEdit chrome. It must not erase the
  // editor's rounded right border or focus ring.
  Result.ButtonInputActionCanvasBackground := Result.InputBackground;
  Result.ButtonTransparent := TAlphaColor($00000000);
  Result.ButtonPrimaryBackground := Result.ButtonPrimary;
  Result.ButtonPrimaryHoverBackground := Result.ButtonPrimaryHover;
  Result.ButtonPrimaryPressedBackground := Result.ButtonPrimaryPressed;
  Result.ButtonPrimaryText := TAlphaColor($FFFFFFFF);
  Result.ButtonSecondaryBackground := Result.ButtonSecondary;
  Result.ButtonSecondaryHoverBackground := Result.ButtonGhostHover;
  Result.ButtonSecondaryPressedBackground := Result.InputBorder;
  Result.ButtonSecondaryBorder := Result.InputBorder;
  Result.ButtonSecondaryHoverBorder := Result.InputBorderHover;
  Result.ButtonSecondaryText := Result.InputText;
  Result.ButtonInputActionText := Result.InputFocus;
  Result.ButtonInputActionDivider := Result.PopupBorder;
  Result.ButtonTransparentText := Result.InputFocus;
  Result.ButtonGhostBackground := Result.ButtonTransparent;
  Result.ButtonGhostActiveBackground := Result.ButtonGhostHover;
  Result.ButtonGhostBorder := Result.InputFocus;
  Result.ButtonGhostText := Result.InputFocus;
  Result.ButtonDangerBackground := Result.ButtonDanger;
  Result.ButtonDangerText := TAlphaColor($FFFFFFFF);
  Result.ButtonWarningBackground := TAlphaColor($FFF5C842);
  Result.ButtonWarningHoverBackground := TAlphaColor($FFFFD54F);
  Result.ButtonWarningPressedBackground := TAlphaColor($FFD98B28);
  Result.ButtonWarningText := Result.InputText;
  Result.ButtonDisabledBackground := Result.InputDisabledBackground;
  Result.ButtonDisabledBorder := Result.InputBorder;
  Result.ButtonDisabledText := Result.InputPlaceholder;
  Result.ButtonLoadingBackground := Result.ButtonPrimaryPressed;
  Result.ButtonLoadingBorder := Result.ButtonPrimaryPressed;
  Result.ButtonLoadingText := TAlphaColor($FFFFFFFF);
  Result.StatusBackground := Result.PopupBackground;
  Result.StatusBorder := Result.PopupBorder;
  Result.StatusIndicator := Result.Success;
  Result.StatusText := Result.InputText;
  Result.StatusTextSecondary := Result.InputHelper;
  Result.ProgressTrack := TAlphaColor($FF263A2C);
  Result.ProgressValueText := Result.InputText;
  Result.ProgressWarning := TAlphaColor($FFF2A93B);
  Result.ProgressDanger := Result.Error;
  Result.ProgressInfo := TAlphaColor($FF4AA3DF);
  Result.ProgressNeutral := Result.InputHelper;
  Result.LoadingSpinnerTrack := Result.InputBorder;
  Result.LoadingAccent := Result.ButtonPrimaryPressed;
  Result.LoadingSkeletonBase := TAlphaColor($FF122418);
  Result.LoadingSkeletonHighlight := TAlphaColor($FF203628);
  Result.PaginationBackground := Result.PopupBackground;
  Result.PaginationBorder := Result.PopupBorder;
  Result.ToastSuccessBackground := TAlphaColor($FF1F8B4C);
  Result.ToastWarningBackground := TAlphaColor($FFB66B12);
  Result.ToastDangerBackground := TAlphaColor($FFB83A38);
  Result.ToastInfoBackground := TAlphaColor($FF246D9E);
  Result.ToastNeutralBackground := TAlphaColor($FF405047);
  Result.ToastSuccessBorder := TAlphaColor($FF74D64A);
  Result.ToastWarningBorder := TAlphaColor($FFFFD54F);
  Result.ToastDangerBorder := TAlphaColor($FFFF7C70);
  Result.ToastInfoBorder := TAlphaColor($FF60A5FA);
  Result.ToastNeutralBorder := TAlphaColor($FF9AA790);
  Result.FeedbackText := TAlphaColor($FFFFFFFF);
  Result.TooltipBackground := TAlphaColor($FF07130C);
  Result.TooltipBorder := TAlphaColor($FF3DB82A);
  Result.TooltipText := Result.FeedbackText;
  Result.ContainerSuiteBackground := Result.PopupBackground;
  Result.ContainerSuiteBorder := Result.PopupBorder;
  Result.ContainerDarkBackground := TAlphaColor($E60E1F15);
  Result.ContainerDarkBorder := TAlphaColor($1CFFFFFF);
  Result.ContainerDarkCardBackground := TAlphaColor($E00C1D13);
  Result.ContainerDarkCardBorder := TAlphaColor($8C43B72B);
  Result.ContainerDarkTitle := TAlphaColor($FFF5F8F5);
  Result.ContainerDarkSubtitle := TAlphaColor($FFB8C1BA);
  Result.ContainerTitle := Result.InputText;
  Result.ContainerSubtitle := Result.InputHelper;
  Result.TabsSurface := TAlphaColor($FF0F1813);
  Result.TabsDivider := TAlphaColor($FF2A3E35);
  Result.TabsTextDefault := TAlphaColor($FFB8C4B8);
  Result.TabsTextHover := TAlphaColor($FFE6F1E6);
  Result.TabsTextActive := TAlphaColor($FFE6F1E6);
  Result.TabsTextDisabled := TAlphaColor($FF667666);
  Result.TabsHoverBackground := TAlphaColor($FF142718);
  Result.TabsActiveBackground := TAlphaColor($FF173A20);
  Result.TabsIndicator := TAlphaColor($FF59FF7A);
  Result.TabsFocus := TAlphaColor($FF46FF8C);
  Result.GridContainerBackground := Result.PopupBackground;
  Result.GridContainerBorder := Result.PopupBorder;
  Result.GridContainerTransparentBackground := Result.TransparentSurfaceFallback;
  Result.GridContainerTransparentBorder := Result.TransparentSurfaceFallback;
  Result.SummaryCardBackground := Result.PopupBackground;
  Result.SummaryCardBorder := Result.PopupBorder;
  Result.SummaryCardDashboardBackground := TAlphaColor($E60E1F15);
  Result.SummaryCardDashboardBorder := TAlphaColor($1CFFFFFF);
  Result.SummaryCardSuccess := TAlphaColor($FF43B72B);
  Result.SummaryCardTitle := Result.InputDisabledText;
  Result.SummaryCardText := Result.InputText;
  Result.SummaryCardFooterNeutral := Result.InputHelper;
  Result.SummaryCardWarning := TAlphaColor($FFF2A93B);
  Result.SummaryCardDanger := Result.Error;
  Result.BadgeSoftBackground := TAlphaColor($FF122418);
  Result.BadgeOutlineBackground := Result.PopupBackground;
  Result.BadgeBorder := Result.PopupBorder;
  Result.BadgeText := Result.InputText;
  Result.SelectorTrack := Result.InputBorder;
  Result.SelectorTrackHover := Result.InputBorderHover;
  Result.SelectorControlBackground := Result.InputBackground;
  Result.SelectorBorder := Result.InputBorder;
  Result.SelectorText := Result.InputText;
  Result.SelectorDisabledText := Result.InputDisabledText;
  Result.SelectorKnob := Result.ButtonSecondary;
  Result.SliderTrack := Result.InputBorder;
  Result.SliderText := Result.InputText;
  Result.ScrollContainerBackground := Result.PopupBackground;
  Result.ScrollContainerBorder := Result.PopupBorder;
  Result.ScrollContainerViewportBackground := TAlphaColor($FF08130D);
  Result.ScrollContainerViewportBorder := Result.TransparentSurfaceFallback;
  Result.ScrollBarTrack := Result.ScrollContainerViewportBackground;
  Result.ScrollBarThumb := Result.TabsDivider;
  Result.ScrollBarThumbHot := Result.InputFocus;
  Result.ScrollBarThumbPressed := Result.Success;
  Result.ScrollBarArrow := Result.TabsTextDefault;
  Result.ScrollBarBorder := Result.TabsDivider;
  Result.ChartDashboardBackground := TAlphaColor($E00C1D13);
  Result.ChartDashboardBorder := TAlphaColor($1CFFFFFF);
  Result.InputChromeBackground := Result.PopupBackground;
  Result.InputUnderlinedBackground := Result.PopupBackground;
  Result.InputIcon := Result.InputBorderHover;
  Result.InputIconDisabled := Result.InputDisabledText;
  Result.InputLabelText := Result.InputText;
  { Required native labels intentionally mirror the selected input border. }
  Result.InputLabelRequiredText := Result.InputFocus;
  Result.InputSupportText := Result.InputHelper;
  Result.InputSupportCounterText := Result.InputDisabledText;
  Result.FieldLabelText := Result.InputLabelText;
  Result.FieldRequiredText := Result.InputLabelRequiredText;
  Result.FieldSupportText := Result.InputSupportText;
  Result.FieldCounterText := Result.InputSupportCounterText;
  Result.FieldSuccessText := Result.Success;
  Result.FieldWarningText := Result.InputWarningSupportText;
  Result.FieldDangerText := Result.Error;
  Result.FieldDisabledText := Result.InputDisabledText;
  Result.InputSuccessBorder := Result.Success;
  Result.InputWarningBorder := TAlphaColor($FFF5C842);
  Result.InputDangerBorder := Result.Error;
  Result.InputWarningSupportText := TAlphaColor($FFD98B28);
  Result.ComboBoxChromeBackground := Result.PopupBackground;
  Result.ComboBoxBackground := Result.InputBackground;
  Result.ComboBoxUnderlinedBackground := Result.PopupBackground;
  Result.ComboBoxDisabledBackground := Result.InputDisabledBackground;
  Result.ComboBoxBorder := Result.InputBorder;
  Result.ComboBoxBorderHover := Result.InputBorderHover;
  Result.ComboBoxFocusBorder := Result.InputFocus;
  Result.ComboBoxSuccessBorder := Result.Success;
  Result.ComboBoxWarningBorder := Result.InputWarningBorder;
  Result.ComboBoxDangerBorder := Result.Error;
  Result.ComboBoxText := Result.InputText;
  Result.ComboBoxDisabledText := Result.InputDisabledText;
  Result.ComboBoxLabelText := Result.InputText;
  Result.ComboBoxHelperText := Result.InputHelper;
  Result.ComboBoxWarningHelperText := Result.InputWarningSupportText;
  Result.ComboBoxCounterText := Result.InputDisabledText;
  Result.ComboBoxIcon := Result.InputBorderHover;
  Result.ComboBoxIconDisabled := Result.InputDisabledText;
  Result.ComboBoxPopupBackground := Result.PopupBackground;
  Result.ComboBoxPopupCanvasBackground := TAlphaColor($00000000);
  Result.ComboBoxPopupBorder := Result.PopupBorder;
  Result.ComboBoxPopupItemText := Result.InputText;
  Result.ComboBoxPopupItemSelectedText := Result.InputFocus;
  Result.ComboBoxPopupItemSelectedBackground := Result.ButtonGhostHover;
  Result.ComboBoxPopupItemHotBackground := Result.ButtonGhostHover;
  Result.ComboBoxPopupCheck := Result.InputFocus;
  Result.ComboBoxPopupSeparator := Result.PopupBorder;
  Result.DateTimeChromeBackground := Result.PopupBackground;
  Result.DateTimeBackground := Result.InputBackground;
  Result.DateTimeDisabledBackground := Result.InputDisabledBackground;
  Result.DateTimeBorder := Result.InputBorder;
  Result.DateTimeBorderHover := Result.InputBorderHover;
  Result.DateTimeFocusBorder := Result.InputFocus;
  Result.DateTimeSuccessBorder := Result.Success;
  Result.DateTimeWarningBorder := Result.ProgressWarning;
  Result.DateTimeDangerBorder := Result.Error;
  Result.DateTimeText := Result.InputText;
  Result.DateTimeDisabledText := Result.InputDisabledText;
  Result.DateTimeLabelText := Result.InputText;
  Result.DateTimeIcon := Result.InputBorderHover;
  Result.DateTimeIconDisabled := Result.InputDisabledText;
  Result.DateTimePopupBackground := Result.PopupBackground;
  Result.DateTimePopupCanvasBackground := TAlphaColor($00000000);
  Result.DateTimePopupBorder := Result.PopupBorder;
  Result.DateTimePopupHeaderText := Result.InputText;
  Result.DateTimePopupWeekText := Result.InputHelper;
  Result.DateTimePopupDayText := Result.InputText;
  Result.DateTimePopupDayDisabledText := Result.InputDisabledText;
  Result.DateTimePopupSelectedBackground := Result.InputFocus;
  Result.DateTimePopupSelectedText := TAlphaColor($FFFFFFFF);
  Result.DateTimePopupTodayBorder := Result.InputBorderHover;
  Result.DateTimePopupTimeValue := Result.InputFocus;
  Result.DateTimePopupActionText := Result.InputText;
  Result.DateTimePopupActionSecondaryText := Result.InputHelper;
  Result.DateTimePopupAcceptBackground := Result.ButtonPrimary;
  Result.DateTimePopupAcceptText := TAlphaColor($FFFFFFFF);
  Result.MemoChromeBackground := Result.PopupBackground;
  Result.MemoBackground := Result.InputBackground;
  Result.MemoDisabledBackground := Result.InputDisabledBackground;
  Result.MemoReadOnlyBackground := Result.InputDisabledBackground;
  Result.MemoText := Result.InputText;
  Result.MemoDisabledText := Result.InputDisabledText;
  Result.MemoReadOnlyText := Result.InputText;
  Result.MemoLabelText := Result.InputText;
  Result.MemoLabelRequiredText := Result.ButtonPrimaryPressed;
  Result.MemoBorder := Result.InputBorder;
  Result.MemoBorderHover := Result.InputBorderHover;
  Result.MemoFocusBorder := Result.InputFocus;
  Result.MemoSuccessBorder := Result.Success;
  Result.MemoWarningBorder := Result.ProgressWarning;
  Result.MemoDangerBorder := Result.Error;
  Result.ChartAccent := Result.Success;
  Result.ChartAccentStrong := Result.Success;
  Result.ChartGrid := Result.ContainerSuiteBorder;
  Result.DataGridBackground := TAlphaColor($FF13261C);
  Result.DataGridHeader := TAlphaColor($FF0F1F16);
  Result.DataGridHeaderText := TAlphaColor($FFE6F2EA);
  Result.DataGridText := TAlphaColor($FFE6F2EA);
  Result.DataGridSecondaryText := TAlphaColor($FFA6B7AE);
  Result.DataGridDisabledText := TAlphaColor($FF5E6E63);
  Result.DataGridRowAlternate := TAlphaColor($FF182C21);
  Result.DataGridHover := TAlphaColor($FF1E3627);
  Result.DataGridFocus := TAlphaColor($FF3DE184);
  Result.DataGridEditing := TAlphaColor($FF1F4D33);
  Result.DataGridSuccess := TAlphaColor($FF2ECC71);
  Result.DataGridError := TAlphaColor($FFE74C3C);
  Result.DataGridLoading := TAlphaColor($FF2C3F34);
  Result.DataGridEmpty := TAlphaColor($FF13261C);
  Result.DataGridSelection := TAlphaColor($FF1F4D33);
  Result.DataGridSelectionBorder := Result.DataGridFocus;
  Result.DataGridHoverBorder := Result.DataGridFocus;
  Result.DataGridBorder := TAlphaColor($FF274233);
  Result.DataGridStatusBackground := Result.DataGridSelection;
  Result.DataGridStatusText := Result.DataGridSuccess;
  Result.DataGridActionBackground := Result.PopupBackground;
  Result.DataGridActionText := Result.Success;
  Result.DataGridActionDangerBackground := Result.ToastDangerBackground;
  Result.DataGridActionDangerText := Result.Error;
  Result.DataGridFooter := Result.DataGridHeader;
  Result.DataGridFooterBackground := Result.DataGridFooter;
  Result.DataGridFooterText := Result.DataGridHeaderText;
  Result.DataGridFooterValueText := Result.DataGridFooterText;
  Result.DataGridPreviewCanvasBackground := Result.DataGridBackground;
  Result.DataGridPreviewFrameBackground := Result.DataGridBackground;
  Result.DataGridPreviewFrameBorder := Result.DataGridBorder;
  Result.DataGridPreviewRowBackground := Result.DataGridRowAlternate;
  Result.DataGridPreviewRowText := Result.DataGridText;
  Result.DataGridPreviewStatusBackground := Result.DataGridStatusBackground;
  Result.DataGridPreviewStatusText := Result.DataGridStatusText;
  Result.DataGridPreviewHeaderBackground := Result.DataGridHeader;
  Result.DataGridPreviewHeaderText := Result.DataGridHeaderText;
  Result.DataGridPreviewFooterBackground := Result.DataGridFooterBackground;
  Result.DataGridPreviewFooterText := Result.DataGridFooterText;
  Result.DataGridPreviewFooterValueText := Result.DataGridPreviewFooterText;
end;

class function TDACControlTokens.Light: TDACControlTokens;
begin
  ConfigureMetrics(Result);
  Result.TransparentSurfaceFallback := TAlphaColor($00000000);
  Result.InputBackground := TAlphaColor($FFFFFFFF);
  Result.InputDisabledBackground := TAlphaColor($FFF0F4F0);
  Result.InputBorder := TAlphaColor($FFB8C4B8);
  Result.InputBorderHover := TAlphaColor($FF9AB9A0);
  Result.InputFocus := TAlphaColor($FF258B3B);
  Result.InputText := TAlphaColor($FF18231C);
  Result.InputPlaceholder := TAlphaColor($FF68756B);
  Result.InputHelper := TAlphaColor($FF58665C);
  Result.InputDisabledText := TAlphaColor($FF758076);
  Result.SystemTextPrimary := Result.InputText;
  Result.SystemTextSecondary := Result.InputHelper;
  Result.SystemTextMuted := Result.InputPlaceholder;
  Result.SystemTextAccent := Result.InputFocus;
  Result.SystemTextSuccess := TAlphaColor($FF258B3B);
  Result.SystemTextWarning := TAlphaColor($FFD88917);
  Result.SystemTextDanger := TAlphaColor($FFC93E3B);
  Result.Success := TAlphaColor($FF258B3B);
  Result.Error := TAlphaColor($FFC93E3B);
  Result.ButtonPrimary := TAlphaColor($FF4DAA33);
  Result.ButtonPrimaryHover := TAlphaColor($FF43982D);
  Result.ButtonPrimaryPressed := TAlphaColor($FF367A23);
  Result.ButtonSecondary := TAlphaColor($FFFFFFFF);
  Result.ButtonGhostHover := TAlphaColor($1F4DAA33);
  Result.ButtonTonal := TAlphaColor($FFDFF0D6);
  Result.ButtonTonalText := TAlphaColor($FF245B1E);
  Result.ButtonDanger := TAlphaColor($FFD9514E);
  Result.ButtonSuccess := TAlphaColor($FF1F8B4C);
  Result.PopupBackground := TAlphaColor($FFFFFFFF);
  Result.PopupBorder := TAlphaColor($FFD7E0D8);
  Result.ButtonFallbackBackground := Result.InputBackground;
  Result.ButtonCanvasBackground := Result.PopupBackground;
  Result.ButtonInputActionCanvasBackground := Result.InputBackground;
  Result.ButtonTransparent := TAlphaColor($00000000);
  Result.ButtonPrimaryBackground := Result.ButtonPrimary;
  Result.ButtonPrimaryHoverBackground := Result.ButtonPrimaryHover;
  Result.ButtonPrimaryPressedBackground := Result.ButtonPrimaryPressed;
  Result.ButtonPrimaryText := TAlphaColor($FFFFFFFF);
  Result.ButtonSecondaryBackground := Result.ButtonSecondary;
  Result.ButtonSecondaryHoverBackground := Result.ButtonGhostHover;
  Result.ButtonSecondaryPressedBackground := Result.InputBorder;
  Result.ButtonSecondaryBorder := Result.InputBorder;
  Result.ButtonSecondaryHoverBorder := Result.InputBorderHover;
  Result.ButtonSecondaryText := Result.InputText;
  Result.ButtonInputActionText := Result.InputFocus;
  Result.ButtonInputActionDivider := Result.PopupBorder;
  Result.ButtonTransparentText := Result.InputFocus;
  Result.ButtonGhostBackground := Result.ButtonTransparent;
  Result.ButtonGhostActiveBackground := Result.ButtonGhostHover;
  Result.ButtonGhostBorder := Result.InputFocus;
  Result.ButtonGhostText := Result.InputFocus;
  Result.ButtonDangerBackground := Result.ButtonDanger;
  Result.ButtonDangerText := TAlphaColor($FFFFFFFF);
  Result.ButtonWarningBackground := TAlphaColor($FFF5C842);
  Result.ButtonWarningHoverBackground := TAlphaColor($FFFFD54F);
  Result.ButtonWarningPressedBackground := TAlphaColor($FFD98B28);
  Result.ButtonWarningText := Result.InputText;
  Result.ButtonDisabledBackground := Result.InputDisabledBackground;
  Result.ButtonDisabledBorder := Result.InputBorder;
  Result.ButtonDisabledText := Result.InputPlaceholder;
  Result.ButtonLoadingBackground := Result.ButtonPrimaryPressed;
  Result.ButtonLoadingBorder := Result.ButtonPrimaryPressed;
  Result.ButtonLoadingText := TAlphaColor($FFFFFFFF);
  Result.StatusBackground := Result.PopupBackground;
  Result.StatusBorder := Result.PopupBorder;
  Result.StatusIndicator := Result.Success;
  Result.StatusText := Result.InputText;
  Result.StatusTextSecondary := Result.InputHelper;
  Result.ProgressTrack := TAlphaColor($FFE2E8F0);
  Result.ProgressValueText := Result.InputText;
  Result.ProgressWarning := TAlphaColor($FFD88917);
  Result.ProgressDanger := Result.Error;
  Result.ProgressInfo := TAlphaColor($FF2B79B8);
  Result.ProgressNeutral := Result.InputHelper;
  Result.LoadingSpinnerTrack := Result.InputBorder;
  Result.LoadingAccent := Result.ButtonPrimaryPressed;
  Result.LoadingSkeletonBase := TAlphaColor($FFE5EBE5);
  Result.LoadingSkeletonHighlight := TAlphaColor($FFF6F8F6);
  Result.PaginationBackground := Result.PopupBackground;
  Result.PaginationBorder := Result.PopupBorder;
  Result.ToastSuccessBackground := TAlphaColor($FF258B3B);
  Result.ToastWarningBackground := TAlphaColor($FFD88917);
  Result.ToastDangerBackground := TAlphaColor($FFC93E3B);
  Result.ToastInfoBackground := TAlphaColor($FF2B79B8);
  Result.ToastNeutralBackground := TAlphaColor($FF58665C);
  Result.ToastSuccessBorder := TAlphaColor($FFBDE5A9);
  Result.ToastWarningBorder := TAlphaColor($FFFFD66B);
  Result.ToastDangerBorder := TAlphaColor($FFFFABA5);
  Result.ToastInfoBorder := TAlphaColor($FF9CC7F2);
  Result.ToastNeutralBorder := TAlphaColor($FFCBD5CB);
  Result.FeedbackText := TAlphaColor($FFFFFFFF);
  Result.TooltipBackground := TAlphaColor($FF18231C);
  Result.TooltipBorder := TAlphaColor($FF258B3B);
  Result.TooltipText := Result.FeedbackText;
  Result.ContainerSuiteBackground := Result.PopupBackground;
  Result.ContainerSuiteBorder := Result.PopupBorder;
  { "Dark" is a serialized appearance name. Its effective palette follows
    ThemeMode so a component under a white parent never retains dark glass. }
  Result.ContainerDarkBackground := TAlphaColor($FFFDFEFD);
  Result.ContainerDarkBorder := Result.PopupBorder;
  Result.ContainerDarkCardBackground := Result.InputBackground;
  Result.ContainerDarkCardBorder := Result.InputBorder;
  Result.ContainerDarkTitle := Result.InputText;
  Result.ContainerDarkSubtitle := Result.InputHelper;
  Result.ContainerTitle := Result.InputText;
  Result.ContainerSubtitle := Result.InputHelper;
  Result.TabsSurface := TAlphaColor($FFFFFFFF);
  Result.TabsDivider := TAlphaColor($FFD7E0D8);
  Result.TabsTextDefault := TAlphaColor($FF5F6D63);
  Result.TabsTextHover := TAlphaColor($FF18231C);
  Result.TabsTextActive := TAlphaColor($FF18231C);
  Result.TabsTextDisabled := TAlphaColor($FF9DA89F);
  Result.TabsHoverBackground := TAlphaColor($FFEAF3EC);
  Result.TabsActiveBackground := TAlphaColor($FFDFF0E2);
  Result.TabsIndicator := TAlphaColor($FF258B3B);
  Result.TabsFocus := TAlphaColor($FF2F9E4A);
  Result.GridContainerBackground := Result.PopupBackground;
  Result.GridContainerBorder := Result.PopupBorder;
  Result.GridContainerTransparentBackground := Result.TransparentSurfaceFallback;
  Result.GridContainerTransparentBorder := Result.TransparentSurfaceFallback;
  Result.SummaryCardBackground := Result.PopupBackground;
  Result.SummaryCardBorder := Result.PopupBorder;
  Result.SummaryCardDashboardBackground := TAlphaColor($FFFDFEFD);
  Result.SummaryCardDashboardBorder := Result.PopupBorder;
  Result.SummaryCardSuccess := TAlphaColor($FF43B72B);
  Result.SummaryCardTitle := Result.InputDisabledText;
  Result.SummaryCardText := Result.InputText;
  Result.SummaryCardFooterNeutral := Result.InputHelper;
  Result.SummaryCardWarning := TAlphaColor($FFD88917);
  Result.SummaryCardDanger := Result.Error;
  Result.BadgeSoftBackground := TAlphaColor($FFE9F3EA);
  Result.BadgeOutlineBackground := Result.PopupBackground;
  Result.BadgeBorder := Result.PopupBorder;
  Result.BadgeText := Result.InputText;
  Result.SelectorTrack := Result.InputBorder;
  Result.SelectorTrackHover := Result.InputBorderHover;
  Result.SelectorControlBackground := Result.InputBackground;
  Result.SelectorBorder := Result.InputBorder;
  Result.SelectorText := Result.InputText;
  Result.SelectorDisabledText := Result.InputDisabledText;
  Result.SelectorKnob := Result.ButtonSecondary;
  Result.SliderTrack := Result.InputBorder;
  Result.SliderText := Result.InputText;
  Result.ScrollContainerBackground := Result.PopupBackground;
  Result.ScrollContainerBorder := Result.PopupBorder;
  Result.ScrollContainerViewportBackground := TAlphaColor($FFF8FAF8);
  Result.ScrollContainerViewportBorder := Result.TransparentSurfaceFallback;
  Result.ScrollBarTrack := Result.ScrollContainerViewportBackground;
  Result.ScrollBarThumb := Result.TabsDivider;
  Result.ScrollBarThumbHot := Result.InputFocus;
  Result.ScrollBarThumbPressed := Result.Success;
  Result.ScrollBarArrow := Result.TabsTextDefault;
  Result.ScrollBarBorder := Result.TabsDivider;
  Result.ChartDashboardBackground := Result.PopupBackground;
  Result.ChartDashboardBorder := Result.PopupBorder;
  Result.InputChromeBackground := Result.PopupBackground;
  Result.InputUnderlinedBackground := Result.PopupBackground;
  Result.InputIcon := Result.InputBorderHover;
  Result.InputIconDisabled := Result.InputDisabledText;
  Result.InputLabelText := Result.InputText;
  { Required native labels intentionally mirror the selected input border. }
  Result.InputLabelRequiredText := Result.InputFocus;
  Result.InputSupportText := Result.InputHelper;
  Result.InputSupportCounterText := Result.InputDisabledText;
  Result.FieldLabelText := Result.InputLabelText;
  Result.FieldRequiredText := Result.InputLabelRequiredText;
  Result.FieldSupportText := Result.InputSupportText;
  Result.FieldCounterText := Result.InputSupportCounterText;
  Result.FieldSuccessText := Result.Success;
  Result.FieldWarningText := Result.InputWarningSupportText;
  Result.FieldDangerText := Result.Error;
  Result.FieldDisabledText := Result.InputDisabledText;
  Result.InputSuccessBorder := Result.Success;
  Result.InputWarningBorder := TAlphaColor($FFF5C842);
  Result.InputDangerBorder := Result.Error;
  Result.InputWarningSupportText := TAlphaColor($FFD98B28);
  Result.ComboBoxChromeBackground := Result.PopupBackground;
  Result.ComboBoxBackground := Result.InputBackground;
  Result.ComboBoxUnderlinedBackground := Result.PopupBackground;
  Result.ComboBoxDisabledBackground := Result.InputDisabledBackground;
  Result.ComboBoxBorder := Result.InputBorder;
  Result.ComboBoxBorderHover := Result.InputBorderHover;
  Result.ComboBoxFocusBorder := Result.InputFocus;
  Result.ComboBoxSuccessBorder := Result.Success;
  Result.ComboBoxWarningBorder := Result.InputWarningBorder;
  Result.ComboBoxDangerBorder := Result.Error;
  Result.ComboBoxText := Result.InputText;
  Result.ComboBoxDisabledText := Result.InputDisabledText;
  Result.ComboBoxLabelText := Result.InputText;
  Result.ComboBoxHelperText := Result.InputHelper;
  Result.ComboBoxWarningHelperText := Result.InputWarningSupportText;
  Result.ComboBoxCounterText := Result.InputDisabledText;
  Result.ComboBoxIcon := Result.InputBorderHover;
  Result.ComboBoxIconDisabled := Result.InputDisabledText;
  Result.ComboBoxPopupBackground := Result.PopupBackground;
  Result.ComboBoxPopupCanvasBackground := TAlphaColor($00000000);
  Result.ComboBoxPopupBorder := Result.PopupBorder;
  Result.ComboBoxPopupItemText := Result.InputText;
  Result.ComboBoxPopupItemSelectedText := Result.InputFocus;
  Result.ComboBoxPopupItemSelectedBackground := Result.ButtonGhostHover;
  Result.ComboBoxPopupItemHotBackground := Result.ButtonGhostHover;
  Result.ComboBoxPopupCheck := Result.InputFocus;
  Result.ComboBoxPopupSeparator := Result.PopupBorder;
  Result.DateTimeChromeBackground := Result.PopupBackground;
  Result.DateTimeBackground := Result.InputBackground;
  Result.DateTimeDisabledBackground := Result.InputDisabledBackground;
  Result.DateTimeBorder := Result.InputBorder;
  Result.DateTimeBorderHover := Result.InputBorderHover;
  Result.DateTimeFocusBorder := Result.InputFocus;
  Result.DateTimeSuccessBorder := Result.Success;
  Result.DateTimeWarningBorder := Result.ProgressWarning;
  Result.DateTimeDangerBorder := Result.Error;
  Result.DateTimeText := Result.InputText;
  Result.DateTimeDisabledText := Result.InputDisabledText;
  Result.DateTimeLabelText := Result.InputText;
  Result.DateTimeIcon := Result.InputBorderHover;
  Result.DateTimeIconDisabled := Result.InputDisabledText;
  Result.DateTimePopupBackground := Result.PopupBackground;
  Result.DateTimePopupCanvasBackground := TAlphaColor($00000000);
  Result.DateTimePopupBorder := Result.PopupBorder;
  Result.DateTimePopupHeaderText := Result.InputText;
  Result.DateTimePopupWeekText := Result.InputHelper;
  Result.DateTimePopupDayText := Result.InputText;
  Result.DateTimePopupDayDisabledText := Result.InputDisabledText;
  Result.DateTimePopupSelectedBackground := Result.InputFocus;
  Result.DateTimePopupSelectedText := TAlphaColor($FFFFFFFF);
  Result.DateTimePopupTodayBorder := Result.InputBorderHover;
  Result.DateTimePopupTimeValue := Result.InputFocus;
  Result.DateTimePopupActionText := Result.InputText;
  Result.DateTimePopupActionSecondaryText := Result.InputHelper;
  Result.DateTimePopupAcceptBackground := Result.ButtonPrimary;
  Result.DateTimePopupAcceptText := TAlphaColor($FFFFFFFF);
  Result.MemoChromeBackground := Result.PopupBackground;
  Result.MemoBackground := Result.InputBackground;
  Result.MemoDisabledBackground := Result.InputDisabledBackground;
  Result.MemoReadOnlyBackground := Result.InputDisabledBackground;
  Result.MemoText := Result.InputText;
  Result.MemoDisabledText := Result.InputDisabledText;
  Result.MemoReadOnlyText := Result.InputText;
  Result.MemoLabelText := Result.InputText;
  Result.MemoLabelRequiredText := Result.ButtonPrimaryPressed;
  Result.MemoBorder := Result.InputBorder;
  Result.MemoBorderHover := Result.InputBorderHover;
  Result.MemoFocusBorder := Result.InputFocus;
  Result.MemoSuccessBorder := Result.Success;
  Result.MemoWarningBorder := Result.ProgressWarning;
  Result.MemoDangerBorder := Result.Error;
  Result.ChartAccent := Result.Success;
  Result.ChartAccentStrong := Result.Success;
  Result.ChartGrid := Result.ContainerSuiteBorder;
  Result.DataGridBackground := TAlphaColor($FFFFFFFF);
  Result.DataGridHeader := TAlphaColor($FFF2F7F3);
  Result.DataGridHeaderText := TAlphaColor($FF1C2B21);
  Result.DataGridText := TAlphaColor($FF1C2B21);
  Result.DataGridSecondaryText := TAlphaColor($FF66786D);
  Result.DataGridDisabledText := TAlphaColor($FF8FA096);
  Result.DataGridRowAlternate := TAlphaColor($FFF6F9F7);
  Result.DataGridHover := TAlphaColor($FFE8F5EC);
  Result.DataGridFocus := TAlphaColor($FF3DE184);
  Result.DataGridEditing := TAlphaColor($FFF1FAF3);
  Result.DataGridSuccess := TAlphaColor($FF2ECC71);
  Result.DataGridError := TAlphaColor($FFE74C3C);
  Result.DataGridLoading := TAlphaColor($FFE7EFE9);
  Result.DataGridEmpty := TAlphaColor($FFFFFFFF);
  Result.DataGridSelection := TAlphaColor($FFDDF3E4);
  Result.DataGridSelectionBorder := Result.DataGridFocus;
  Result.DataGridHoverBorder := Result.DataGridFocus;
  Result.DataGridBorder := TAlphaColor($FFD6E3D9);
  Result.DataGridStatusBackground := Result.DataGridSelection;
  Result.DataGridStatusText := TAlphaColor($FF187A46);
  Result.DataGridActionBackground := Result.PopupBackground;
  Result.DataGridActionText := Result.Success;
  Result.DataGridActionDangerBackground := Result.ToastDangerBackground;
  Result.DataGridActionDangerText := Result.Error;
  Result.DataGridFooter := Result.DataGridHeader;
  Result.DataGridFooterBackground := Result.DataGridFooter;
  Result.DataGridFooterText := Result.DataGridHeaderText;
  Result.DataGridFooterValueText := Result.DataGridFooterText;
  Result.DataGridPreviewCanvasBackground := Result.DataGridBackground;
  Result.DataGridPreviewFrameBackground := Result.DataGridBackground;
  Result.DataGridPreviewFrameBorder := Result.DataGridBorder;
  Result.DataGridPreviewRowBackground := Result.DataGridRowAlternate;
  Result.DataGridPreviewRowText := Result.DataGridText;
  Result.DataGridPreviewStatusBackground := Result.DataGridStatusBackground;
  Result.DataGridPreviewStatusText := Result.DataGridStatusText;
  Result.DataGridPreviewHeaderBackground := Result.DataGridHeader;
  Result.DataGridPreviewHeaderText := Result.DataGridHeaderText;
  Result.DataGridPreviewFooterBackground := Result.DataGridFooterBackground;
  Result.DataGridPreviewFooterText := Result.DataGridFooterText;
  Result.DataGridPreviewFooterValueText := Result.DataGridPreviewFooterText;
end;

end.
